{
  "name": "MantencionCD",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "es-CL",
    "sourceQueryCulture": "es-CL",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": false,
    "tables": [
      {
        "name": "Maquinas",
        "lineageTag": "1a2af3c8-00fc-40fe-a407-488a1ad0054b",
        "columns": [
          {
            "name": "ID_Maquina",
            "dataType": "string",
            "sourceColumn": "ID_Maquina",
            "lineageTag": "4e4a052c-307a-45c1-b44e-aba26cd94d18"
          },
          {
            "name": "Nombre",
            "dataType": "string",
            "sourceColumn": "Nombre",
            "lineageTag": "ad098d15-eddc-44f3-a1bb-5ad97a071290"
          },
          {
            "name": "Tipo",
            "dataType": "string",
            "sourceColumn": "Tipo",
            "lineageTag": "afcdd4cf-07ab-4828-ab62-17a6d196fc38"
          },
          {
            "name": "Zona",
            "dataType": "string",
            "sourceColumn": "Zona",
            "lineageTag": "c7671368-4e6f-42e5-a113-c9b17423edec"
          },
          {
            "name": "Criticidad",
            "dataType": "string",
            "sourceColumn": "Criticidad",
            "lineageTag": "9c60a933-6284-475a-b1b5-626ca4ccaeeb"
          },
          {
            "name": "Fabricante",
            "dataType": "string",
            "sourceColumn": "Fabricante",
            "lineageTag": "e8cc732c-7f05-4f1f-bf92-918e5a6b38bb"
          },
          {
            "name": "Anio_Instalacion",
            "dataType": "int64",
            "sourceColumn": "Anio_Instalacion",
            "lineageTag": "a7efe167-4223-4036-a0a8-44bce678328b",
            "summarizeBy": "none"
          },
          {
            "name": "Maquina",
            "dataType": "string",
            "sourceColumn": "Maquina",
            "lineageTag": "1455df83-4cb0-4a26-8822-da4de3317d65"
          }
        ],
        "partitions": [
          {
            "name": "Maquinas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // DATOS DE EJEMPLO INCRUSTADOS — para conectar tu Google Sheet, reemplaza",
                "    // todo este código por power-query/conector-google-sheets/Maquinas.m",
                "    Datos = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rZVNb9MwGMe/irXzEOVx0nItGQymAlKLdpl2sByLWWRx5bhI+zgcOXPgTr8YdvwWu2hhyVSp9cuj3+8f23Fvbs42l9cvFq/Ozk0D+Yb+rrikB64Est11o4j+edswpSSnrxe6Awtw9ZqA/vxGDnF77rDgsTAVCwELEYs9Fk/F4oDFEVt4bPFELHhsEbBFxJYeW07FlgFb9tjd+ovdsh1Rx58NVwylXd1+I2r2laCaIUnot06PfGQ1N5r1QYn7OxJXxOKMI+EFE6QmmGmCzATRhFMTnmnCmQlHU5GaipmmIjMV0VSmpnKaCbypzEyDE7FMTcuZpmVmWkbTKjWtZppWmWnVm6pP7mKqRPudPQiJWKskqQnaS1EfKOXHX+1gWje3jLJ9P57VuDfsQ6uYlKJp4vZZiwnwqCYEgmGgjjRcF+pPW7OWdWmaC9btCb0T6CVah/mRJJAkOeGbGFefN3ZdrkQj9CwlUi82MSt7/KE47ReeknsurNGWjeRxrPcPtSQxlnlYqzOx/stnEm6rnU241dtv62shWWcKO7/NHeof2k0OxvvD1Diqnh0cn3dStPzQxTWzJhNuTBVywWgueKZcMJ7L3n3V5tKddG81l30+8Ij/X/9zFtofp5QajJAb4RmMcGIcPCPOjXi6EbwRnxj1PX/7Fw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"ID_Maquina\" = _t, #\"Nombre\" = _t, #\"Tipo\" = _t, #\"Zona\" = _t, #\"Criticidad\" = _t, #\"Fabricante\" = _t, #\"Anio_Instalacion\" = _t, #\"Maquina\" = _t]),",
                "    Tipos = Table.TransformColumnTypes(Datos, {{\"ID_Maquina\", type text}, {\"Nombre\", type text}, {\"Tipo\", type text}, {\"Zona\", type text}, {\"Criticidad\", type text}, {\"Fabricante\", type text}, {\"Anio_Instalacion\", Int64.Type}, {\"Maquina\", type text}}, \"es-CL\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Bitacora",
        "lineageTag": "a4c0c8f4-15a8-48a9-a846-a69caf10a366",
        "columns": [
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "lineageTag": "e68fba18-c8db-4b37-8e7f-6d18858d28a8",
            "formatString": "dd-MM-yyyy"
          },
          {
            "name": "Turno",
            "dataType": "string",
            "sourceColumn": "Turno",
            "lineageTag": "92e682c0-5e2a-4e51-92e6-bfecf572c26d",
            "sortByColumn": "TurnoNum"
          },
          {
            "name": "Tecnico",
            "dataType": "string",
            "sourceColumn": "Tecnico",
            "lineageTag": "a5131447-6d25-4a4b-9475-7134df8b7945"
          },
          {
            "name": "ID_Maquina",
            "dataType": "string",
            "sourceColumn": "ID_Maquina",
            "lineageTag": "44f7264a-37a8-4b1a-9232-1920908c75a7"
          },
          {
            "name": "Tipo_Actividad",
            "dataType": "string",
            "sourceColumn": "Tipo_Actividad",
            "lineageTag": "ce8e0218-9d69-4672-b2e1-88d9c64ae8c2"
          },
          {
            "name": "Descripcion",
            "dataType": "string",
            "sourceColumn": "Descripcion",
            "lineageTag": "042baac8-ca6a-4bf3-b7e6-9d8527051e8e"
          },
          {
            "name": "Estado_Maquina",
            "dataType": "string",
            "sourceColumn": "Estado_Maquina",
            "lineageTag": "bc2fb7ba-cb54-4c96-92b4-2b2b83c749a2"
          },
          {
            "name": "Detencion_Min",
            "dataType": "int64",
            "sourceColumn": "Detencion_Min",
            "lineageTag": "a9e6b9b5-54f8-4701-8cd1-2546b4364144",
            "summarizeBy": "none"
          },
          {
            "name": "Pendiente",
            "dataType": "string",
            "sourceColumn": "Pendiente",
            "lineageTag": "de63df66-8ef3-48e8-8985-d3066d2a0de1"
          },
          {
            "name": "Observaciones",
            "dataType": "string",
            "sourceColumn": "Observaciones",
            "lineageTag": "a08b4f82-0522-4768-af6a-82d3145dbab5"
          },
          {
            "name": "Clase_Mantencion",
            "dataType": "string",
            "sourceColumn": "Clase_Mantencion",
            "lineageTag": "5263c07f-afb4-43a1-b288-04dc37a4a4c7"
          },
          {
            "name": "TurnoNum",
            "dataType": "int64",
            "type": "calculated",
            "isHidden": true,
            "lineageTag": "4060ede2-2abd-493c-ae98-86db87726fea",
            "summarizeBy": "none",
            "expression": "SWITCH ( Bitacora[Turno], \"Mañana\", 1, \"Tarde\", 2, \"Noche\", 3, 4 )"
          }
        ],
        "partitions": [
          {
            "name": "Bitacora",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // DATOS DE EJEMPLO INCRUSTADOS — para conectar tu Google Sheet, reemplaza",
                "    // todo este código por power-query/conector-google-sheets/Bitacora.m",
                "    Datos = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"xVlNb9s4EP0rRE67gLOwZTux01PqfmB30yZIgl6KHmiJdrilSZWSjE3+TY576GHRW6/+Y/uGkmjZsmS7PSyKtpIhi4/DN2/ejD9+PAm6wdlp9/w06J50Tt7x1b9cc1xNuFUmYS8tXxrcXr39cNrt4eJ3ncQiDOXqm8bdrdERZ5FgUstQGrpKM6vNBQulDTOZGoZvdlhos1Ak7JFZMVMiTI3FXSI102YpIh6J5De87ToWlqdySesTmvdYWWdKYZ0slYD1qdOI9w++lPg2uzMp4Z28L/BeyUUsxROvXBLKGR4LhYp4DiqV1oGfSbVgPLU85pFhQjNc6mQmrNCh5Ow++DGY99xGguDKeSYUu119NQlu7y7vT7t9XFz+lSWp8BcujCZGiHAhNDAgyAATcqUE6wUXDC9JeLr6R8m0eGJK20q4kloA+gZMFhrNrqeJsEteHlxvSOuvvuLfD3IuFbflQkl1pZPmPb034QNBfiOUjAW7BFGEO4nbyd0uqkwexJdMUJQVszz8THsLuZ3zC5YKnUijsd/YWPxNpPsSTgavTAEuv9XGLrj6Ear02qjtqXIrYm59hCZ8Mc0ZbU0klTLMRdnTYmHY6wFdJOAPcOfHZgiXe8U2yv6wgHnyBsHl7M1pDq9PS0+MtUgLerIGvCTPxOgk5Rr8fbX6yp/ok6u3OfJ3XKfEUIrSjRUuam7Rm3dsgeBmXF0wVaE/GFFkYQdMszgY+nRqrHZZGttMTLk/oe2tDMqIn1zfn5ZYeyNab714bR8lYW5NZOXcsBupUy8txLTL2Dwaxtm1jyF9GJpFTEe3kHixC34suGMP+B7z8MFgC3b1PJOhExsnK3g12E4hIVq1E+YaZ7iJNmhTlj+urwplyaZWhh5o9TaPXIR8cCkcK57yGbHXic1SJuVDWi6RDg8ywgYyhR0cz+1gj74ENWbfeeUArCQkSpNCxJTzKVARUrFWgdEFMOMxPL/BDBmqGtxe0G1gedDC8qBNTlx6BvXKUw2jAEXUItfLKde5WpIY4gp/NE6CmA7CzDnpqwJL90pk1yvkjTVzJDw0MvSi4JZpkMf+3ko6ODRpEW5IcofNUIEM/sc5aC0sIUjEPLPYYeRIhVRQkUOGo149L0RqTY34412J68A0JW6/VYCc1NfP5oOwclbNBSfwxXVxLJtKXypNhw4OJXdeZ9b+TOjvE5l+LRVILyCK2B9TBnSXTwVoYj95Fjbpbypn1cBQ3OlL0wbJHzZJfr8lGQZt4uMyurdRnV4iMS3OY+PDafEhIG7JfsoBPvEBd+XYW4nj1WfQrD6+rq7djXMn/sTzTEVShhWPk1dWioxhtzW7FRyGqFFMXPwOTr4yipR3+Gz1jQS+U+TkWgy9UkI78HSNucOdWTduybrhXgEZNlvbUiLU6hl6VpgoXpQijUjM10cAUs6USTkVzuMPf9gqDr5Qbvsqqou0OLcwT6l1tGQiUXzqUNG+I3QQCSUblF1xvDSnxSN9mEe95kmacm3QkmtnG3He1gxP4F09zxwlxXJVZNVSPBqbEDUkRJjr1Tc4VWdWrIgykgv2+vyYiiMiaclXZiJJjX9JQ705a6O879x22qu7DHeVSrrhpAqv1WE8b0uQGMaVnthK40qPSLxSJnsUu26zzvcq3fAHMrWqd+usrVsXRsYShqdeaXbb225Lvp63qCB59KCqgkgHV/eMLj0tIM0zUuuKM3c9Hh2CJhrNuQ4fqMcD4xD8BfKaLK6uow+Ge9N2tLcbClq6Ia/aZKX4bqtF3mT1ndijI9qicGUmCLB8LdojH+0Jzh8EMJWk8DarKYNHrRLkW4umVhSSbSXUJq/mKdSGkGU2F0swNv9O5yd6z1GLK/EDgCaDHgkcMkkK2SVf1PncpNWRQNWghzUPsA35vEkphy1xHrcOW4jj/f+hDx3uSNSgLVHHB9iVTa5U7gjHAju2pRwDY16Xwswu0YZWBlrH82S8V8QHdaLs6gbyXi4f5cy4SnhSifmjr6mOIwtIY3N3v8WPs2Z+9FuHh94JHMSPdbfcKZvoDpgg8hq17pUrmk5bBvHdA86E1WRxvIsqbgjWQJV+t330sndotK77Dl6llodyipR+sQmevPj1nzU17zUdxvmew2iVnLMGUzM1kZjnbQ4PP1NOCiWolSyKk28UkkIQj6Z5v9cmJL5LO4goFXku2+Oqvd3sihHlGRK+oVOrzC2qHr3fwo/enrnLeWPZgd3KnHPcHOLmWv6CrbcIQcF711X0GAP5juUo3DQ7oWrxS5X5wa8nzeezfxaz00u6+u0EfCGgOdw9I7Sf0zHxd0pbiQqpnBGjjxvOjUodaVAaz+6tNh9Z4oo6AK6eU2hHPpcr5w9Fs1H08sAcIhGodfpCrR7toWpK9h7DeH0OW1k72n5XUxYXGz1AgCpd4K3/HeMpg180ZM4tVSN3Vc6xq78q1HvV9gQuYDWJS0PLd7OefxbDFi/nILnTPlvq9wWbZfPc2jiM1emog/sqt0QO7VljoMeMT7FUShOlhDaoacpZf2NL/A+bAm/pv4FS6NV3XvFhO1Z9sS4HSPl8u0Cf0mlv7TEYtOwx14dipwdv5Wd/2vMTA7Kb+Q97P/NTXoGvQUu9hT+gJJAxRkzXU9OGaenaVlLd2P65DNdn9WpQoKxWg0//AQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Fecha\" = _t, #\"Turno\" = _t, #\"Tecnico\" = _t, #\"ID_Maquina\" = _t, #\"Tipo_Actividad\" = _t, #\"Descripcion\" = _t, #\"Estado_Maquina\" = _t, #\"Detencion_Min\" = _t, #\"Pendiente\" = _t, #\"Observaciones\" = _t, #\"Clase_Mantencion\" = _t]),",
                "    Tipos = Table.TransformColumnTypes(Datos, {{\"Fecha\", type date}, {\"Turno\", type text}, {\"Tecnico\", type text}, {\"ID_Maquina\", type text}, {\"Tipo_Actividad\", type text}, {\"Descripcion\", type text}, {\"Estado_Maquina\", type text}, {\"Detencion_Min\", Int64.Type}, {\"Pendiente\", type text}, {\"Observaciones\", type text}, {\"Clase_Mantencion\", type text}}, \"es-CL\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actividades",
            "expression": [
              "COUNTROWS ( Bitacora )"
            ],
            "lineageTag": "6fdb9a1b-4c47-437d-a9b6-cd31375e1d26",
            "formatString": "#,0"
          },
          {
            "name": "Actividades Pendientes",
            "expression": [
              "CALCULATE ( COUNTROWS ( Bitacora ), Bitacora[Pendiente] = \"Sí\" )"
            ],
            "lineageTag": "d90f8f24-2a5f-4023-a51c-1bba1aae3803",
            "formatString": "#,0"
          },
          {
            "name": "Horas Detencion Bitacora",
            "expression": [
              "DIVIDE ( SUM ( Bitacora[Detencion_Min] ), 60 )"
            ],
            "lineageTag": "7183d514-8116-400d-8184-e5737197ba8e",
            "formatString": "#,0.0"
          },
          {
            "name": "Turnos Con Registro",
            "expression": [
              "COUNTROWS ( SUMMARIZE ( Bitacora, Bitacora[Fecha], Bitacora[Turno] ) )"
            ],
            "lineageTag": "3eb58b76-678d-4f42-8152-b9842959629b",
            "formatString": "#,0"
          },
          {
            "name": "Mantenciones Preventivas",
            "expression": [
              "CALCULATE ( COUNTROWS ( Bitacora ), Bitacora[Clase_Mantencion] = \"Preventiva\" )"
            ],
            "lineageTag": "e3fda7bb-8521-4116-b1f3-936072664577",
            "formatString": "#,0"
          },
          {
            "name": "Mantenciones Correctivas",
            "expression": [
              "CALCULATE ( COUNTROWS ( Bitacora ), Bitacora[Clase_Mantencion] = \"Correctiva\" )"
            ],
            "lineageTag": "1cf4ddd7-6720-4143-a4da-34a8bf1fd1a5",
            "formatString": "#,0"
          },
          {
            "name": "Mantenciones de Rutina",
            "expression": [
              "CALCULATE ( COUNTROWS ( Bitacora ), Bitacora[Clase_Mantencion] = \"Rutina\" )"
            ],
            "lineageTag": "01b3237f-2874-4f2c-9b73-8aace1934f21",
            "formatString": "#,0"
          },
          {
            "name": "% Trabajo Planificado",
            "expression": [
              "DIVIDE (",
              "    [Mantenciones Preventivas] + [Mantenciones de Rutina],",
              "    [Mantenciones Preventivas] + [Mantenciones de Rutina] + [Mantenciones Correctivas]",
              ")"
            ],
            "lineageTag": "9ac50e9f-5baa-456b-aed4-6e030f38dda5",
            "formatString": "0%"
          }
        ]
      },
      {
        "name": "Fallas",
        "lineageTag": "ff9b4e64-3390-45d6-8e0e-ac4dfb0c0993",
        "columns": [
          {
            "name": "ID_Falla",
            "dataType": "string",
            "sourceColumn": "ID_Falla",
            "lineageTag": "1823ba95-14cf-4fd3-92a0-cd518258d36c"
          },
          {
            "name": "Fecha_Hora_Falla",
            "dataType": "dateTime",
            "sourceColumn": "Fecha_Hora_Falla",
            "lineageTag": "0100ccf2-498c-4c6a-a348-270af604561f",
            "formatString": "dd-MM-yyyy HH:mm"
          },
          {
            "name": "ID_Maquina",
            "dataType": "string",
            "sourceColumn": "ID_Maquina",
            "lineageTag": "e201378d-d3ef-415e-8d3f-98013bfab27c"
          },
          {
            "name": "Turno_Detecta",
            "dataType": "string",
            "sourceColumn": "Turno_Detecta",
            "lineageTag": "831368a5-7856-4be6-8f24-96b7e43f1cf7"
          },
          {
            "name": "Tipo_Falla",
            "dataType": "string",
            "sourceColumn": "Tipo_Falla",
            "lineageTag": "5eccdb56-dc20-48af-9083-32d7f1e03b67"
          },
          {
            "name": "Severidad",
            "dataType": "string",
            "sourceColumn": "Severidad",
            "lineageTag": "4845984d-93a4-4807-96e8-0614208894a8"
          },
          {
            "name": "Descripcion_Falla",
            "dataType": "string",
            "sourceColumn": "Descripcion_Falla",
            "lineageTag": "a8b7e810-d71c-4243-b7bb-87abf7e8276d"
          },
          {
            "name": "Estado",
            "dataType": "string",
            "sourceColumn": "Estado",
            "lineageTag": "d36a8a86-446c-4eff-9d70-8692c52a0b76"
          },
          {
            "name": "Fecha_Hora_Cierre",
            "dataType": "dateTime",
            "sourceColumn": "Fecha_Hora_Cierre",
            "lineageTag": "f9889e0f-7a7a-47d3-87eb-760857cb1b43",
            "formatString": "dd-MM-yyyy HH:mm"
          },
          {
            "name": "Detencion_Min",
            "dataType": "int64",
            "sourceColumn": "Detencion_Min",
            "lineageTag": "a301a6e6-870f-4611-864c-99a64269e034",
            "summarizeBy": "none"
          },
          {
            "name": "Reparacion_Realizada",
            "dataType": "string",
            "sourceColumn": "Reparacion_Realizada",
            "lineageTag": "70dfa866-eabc-45e4-b0e2-8171e9d7859c"
          },
          {
            "name": "Repuestos_Usados",
            "dataType": "string",
            "sourceColumn": "Repuestos_Usados",
            "lineageTag": "e1725565-4ec7-43fa-9c72-a43b2630ba84"
          },
          {
            "name": "Tecnico_Responsable",
            "dataType": "string",
            "sourceColumn": "Tecnico_Responsable",
            "lineageTag": "a7020446-5156-4ebd-bb84-88b5165d3f93"
          },
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "lineageTag": "94732cd0-f3e0-41a9-9e31-146f8466c06f",
            "formatString": "dd-MM-yyyy"
          }
        ],
        "partitions": [
          {
            "name": "Fallas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // DATOS DE EJEMPLO INCRUSTADOS — para conectar tu Google Sheet, reemplaza",
                "    // todo este código por power-query/conector-google-sheets/Fallas.m",
                "    Datos = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jVfLbhs3FP0VQqsWsNN56tWVozgtAicx5CABGmRBzVAyHYpUyRkH1pd062UXWRT5BP1Y772cpz1SCwPWzHCG93XOuZefP49en0dBND4PonR0NvKX4/NoxsJgHgXw6Oq3j+cBrr3lh3+45nC1MLqwRrFf2I1ZF9+4FfDwQhXcv852UthcsMxsSy0znsnDDw13mgnFrq8WDNYKe3hcy8wwodneaI7PMltmwr1AA8JanvMnDoVz8iPBf0shYWtp8LuLa/ZNriV7YBnfrvwzrguBu6LPOcc9L/wTfBODkZsSvFkevhvXMzP6ctbJybhZm8AdC9N5gjlZvIOcRHDxgUOguJ3IDo8YK13nEn9fcp1jXC4TkC7wglmz50y4AuIsSssxdseVhBX407nQw9F70+N5jKbTgHIttajyCsGuyNID43elKwQ+ASPtshWFsdrA1rpU6mz0ht9DgTgUrzA9I/3YJ921lAXxPETbNxcfzoMELt6Z7FZQnIWwh+8c4LDgdsNbLNzw4vC3kuCSNozqxRkErs0cXK4+chKggZ8BJLhjisO7sC/mBupjefb1SErAo7GvRkR+XRsnfcgxBO0/hYu1gFwbx+cdcKxLJ1dKQMZc4yFnu2YDrsA5Tah5Xb06ji/wTii5A8BZfi9035t+7qbdtSkLIw/dAS7dCO0OP6yHzkt+R88yrrWw6KoTm9ICQnLijxIEHAfJBA+34Df8HsMMmY3RGgHnSm6Bl3vEiRU+VuDdVsIWlBTI/Ba8oNw570CDGCA8AErDx6+gZvuelX7gs85aGLBwOiddIdCk/0GYZSmIMMATCBgJgjHflWIDgEGvmmLdy5WnDzidcaXEcArQgdmcGDNF44sGAZZMPTAgxp+loJjFHe3inag9OKYUuHcvcEpxsxazKJonTcXDDlve74B6lHrV1QplwA/TU0ZSUmPZDgMs2JYrWL7jOWkmaSVbREcCBwdiL98EgFfC7SA+itN/CVp5y61C5THeIwB+U++lya3cGHYNODO9fftBh521KGTBdB6mtTyGPZgP1tvkUimDxF9hWBsQQCirLSXcPICzBYATE8K3hl0mw6F6s2kT6lKI7U7xvamARBYQ8vfS1YJIOzqgucD+YIhAtTOHv2gvUDIFr7wEppuetX4Cou4aiHTiRZrg3u0P/ao/k0decKAcRI2Ar+oN0mXsloSQIM6mRxLQ9oaQKr6EjsMLX+yGMmfYBaQ19LSy8MB2wIOV770yU22HOIL5qN8h4ri7RpALm4kh7mC+p3HP5wRlIEC5rxpWC+4YBVo0OEAuNHJ4JBcJCwIvtWna1TzqgmuUT2OFIzygzZVtu6QGTd/8Tx5ET3iQdNdSrAeB6M37K8+DU6q34Lnw8w+HcGA4EH5UcoqvyDUaYYj0gOuCIyr4kfDB9MRLfvKMC55GWGpvcKj6ow/0kn9jdEr3o37Di9Pu2pRFoW/NRIT49LBQJ6KlA1RcaFkJHWEfa9+MDHxjimqoG8jBFLWXqj9JWzacddp/s9ETWYC0w9RUeD1oHI2Sj6MTSOj3v7g7MMLMCq6ETRtIjlGiycBQ369UcccxUMfWXDn4QTRwh4p1JA2zJg1Jr/vvrFmXfly0XXhQ77f8oUrsW7ytxoBTg8+TgTnuDo0xtN+qCzUdYYgJlSIsRV4iP9nlhBjg+4AT98KigjuzAgkDjyEbOAQNx402K/b5sbDT8+v94VyyA/0zLQXQHA2hL7p+3Fx+YuGL9Ounk0yInwwC7eg3hZBZMOu0hPHx0a+WxXrCg8gOjwWsOfS9nU1zPEyYZsJFhy81WwrEB71Ra9fM94KnMid0ZnJhf0UEmZUT9r5am0Tsth34htofxtOPddaPFRtA2tW9Gu2/yxyiKZUPdQG8KvzldaNodTPYgT5XQ7gviUXm4pM5zO0bmvr8gUqx23ZbOuGtYAvMoo8hCeiohDMijj/WK93zT9lPoDCwcRDhzOyHygJh+rOH2LMPjsrBswQlQXctYsHEQ3NgQOpPCNVB4I9SZ7cG2Q7ghSbg6mao69HG+ZrS+XKIEd7s1DdmomI9Cw5OgJ5l7azA9t6D02fHKZ0dv/wL\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"ID_Falla\" = _t, #\"Fecha_Hora_Falla\" = _t, #\"ID_Maquina\" = _t, #\"Turno_Detecta\" = _t, #\"Tipo_Falla\" = _t, #\"Severidad\" = _t, #\"Descripcion_Falla\" = _t, #\"Estado\" = _t, #\"Fecha_Hora_Cierre\" = _t, #\"Detencion_Min\" = _t, #\"Reparacion_Realizada\" = _t, #\"Repuestos_Usados\" = _t, #\"Tecnico_Responsable\" = _t, #\"Fecha\" = _t]),",
                "    Tipos = Table.TransformColumnTypes(Datos, {{\"ID_Falla\", type text}, {\"Fecha_Hora_Falla\", type datetime}, {\"ID_Maquina\", type text}, {\"Turno_Detecta\", type text}, {\"Tipo_Falla\", type text}, {\"Severidad\", type text}, {\"Descripcion_Falla\", type text}, {\"Estado\", type text}, {\"Fecha_Hora_Cierre\", type datetime}, {\"Detencion_Min\", Int64.Type}, {\"Reparacion_Realizada\", type text}, {\"Repuestos_Usados\", type text}, {\"Tecnico_Responsable\", type text}, {\"Fecha\", type date}}, \"es-CL\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Maquinas Intervenidas",
            "expression": [
              "DISTINCTCOUNT ( Bitacora[ID_Maquina] )"
            ],
            "lineageTag": "dd00bbfb-7c13-48f1-b738-8cab34c4c63d",
            "formatString": "#,0"
          },
          {
            "name": "Numero Fallas",
            "expression": [
              "COUNTROWS ( Fallas )"
            ],
            "lineageTag": "a3b08840-fbe3-4458-92e2-db112bf58a63",
            "formatString": "#,0"
          },
          {
            "name": "Fallas Abiertas",
            "expression": [
              "CALCULATE ( COUNTROWS ( Fallas ), Fallas[Estado] <> \"Cerrada\" )"
            ],
            "lineageTag": "8e85ad7d-154e-4c82-9da8-d67e5235b594",
            "formatString": "#,0"
          },
          {
            "name": "Fallas Abiertas (actual)",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( Fallas ),",
              "    Fallas[Estado] <> \"Cerrada\",",
              "    REMOVEFILTERS ( Calendario )",
              ")"
            ],
            "lineageTag": "f63b3eff-8ad8-4c4d-aae2-478bf5126bfe",
            "formatString": "#,0"
          },
          {
            "name": "Fallas Criticas",
            "expression": [
              "CALCULATE ( COUNTROWS ( Fallas ), Fallas[Severidad] = \"Crítica\" )"
            ],
            "lineageTag": "71dc6458-8076-46c2-a3b2-91d02ab174c5",
            "formatString": "#,0"
          },
          {
            "name": "Maquinas Con Falla Abierta",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( Fallas[ID_Maquina] ),",
              "    Fallas[Estado] <> \"Cerrada\",",
              "    REMOVEFILTERS ( Calendario )",
              ")"
            ],
            "lineageTag": "a981212b-88e8-45d6-a857-a1815f005149",
            "formatString": "#,0"
          },
          {
            "name": "Equipos Con Falla",
            "expression": [
              "DISTINCTCOUNT ( Fallas[ID_Maquina] )"
            ],
            "lineageTag": "34443f3f-2ca5-4328-a475-bbefef0d013e",
            "formatString": "#,0"
          },
          {
            "name": "Minutos Detencion Fallas",
            "expression": [
              "SUM ( Fallas[Detencion_Min] )"
            ],
            "lineageTag": "133a179f-6ab1-41ab-a18a-4d6b0dc6137e",
            "formatString": "#,0"
          },
          {
            "name": "Horas Detencion Fallas",
            "expression": [
              "DIVIDE ( [Minutos Detencion Fallas], 60 )"
            ],
            "lineageTag": "2108e2e5-44b5-4804-9859-07e5cf2dc661",
            "formatString": "#,0.0"
          },
          {
            "name": "MTTR Horas",
            "expression": [
              "DIVIDE (",
              "    CALCULATE ( AVERAGE ( Fallas[Detencion_Min] ), Fallas[Estado] = \"Cerrada\" ),",
              "    60",
              ")"
            ],
            "lineageTag": "fe2fb8f1-92ed-40b1-911c-9bf08e17d40c",
            "formatString": "#,0.0"
          },
          {
            "name": "Horas Operacion por Dia",
            "expression": [
              "24"
            ],
            "lineageTag": "65548485-60d9-4d1f-9ef3-6ae808eaee12",
            "formatString": "#,0"
          },
          {
            "name": "Horas Operacion Estimadas",
            "expression": [
              "[Horas Operacion por Dia]",
              "    * COUNTROWS ( Calendario )",
              "    * DISTINCTCOUNT ( Maquinas[ID_Maquina] )"
            ],
            "lineageTag": "608fc21f-7864-45c7-ae73-c98640dc7e87",
            "formatString": "#,0"
          },
          {
            "name": "MTBF Horas",
            "expression": [
              "DIVIDE (",
              "    [Horas Operacion Estimadas] - [Horas Detencion Fallas],",
              "    [Numero Fallas]",
              ")"
            ],
            "lineageTag": "4c616cd6-c1a2-4542-9252-b69877dfaf8a",
            "formatString": "#,0.0"
          },
          {
            "name": "Disponibilidad %",
            "expression": [
              "DIVIDE (",
              "    [Horas Operacion Estimadas] - [Horas Detencion Fallas],",
              "    [Horas Operacion Estimadas]",
              ")"
            ],
            "lineageTag": "46a0b41b-0a90-41b7-87f5-e820f04b20fd",
            "formatString": "0%"
          },
          {
            "name": "Antiguedad Backlog Dias",
            "expression": [
              "AVERAGEX (",
              "    CALCULATETABLE (",
              "        FILTER ( Fallas, Fallas[Estado] <> \"Cerrada\" ),",
              "        REMOVEFILTERS ( Calendario )",
              "    ),",
              "    INT ( TODAY () - Fallas[Fecha] )",
              ")"
            ],
            "lineageTag": "a4636689-fc86-4fce-8bba-ee2ce59c3a59",
            "formatString": "#,0.0"
          },
          {
            "name": "Antiguedad Backlog Max Dias",
            "expression": [
              "MAXX (",
              "    CALCULATETABLE (",
              "        FILTER ( Fallas, Fallas[Estado] <> \"Cerrada\" ),",
              "        REMOVEFILTERS ( Calendario )",
              "    ),",
              "    INT ( TODAY () - Fallas[Fecha] )",
              ")"
            ],
            "lineageTag": "a4405eda-1d4e-49ff-ae39-0a3eeae4d3fe",
            "formatString": "#,0"
          },
          {
            "name": "% Fallas Resueltas Mismo Dia",
            "expression": [
              "VAR Cerradas =",
              "    FILTER (",
              "        Fallas,",
              "        Fallas[Estado] = \"Cerrada\" && NOT ISBLANK ( Fallas[Fecha_Hora_Cierre] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        COUNTROWS (",
              "            FILTER ( Cerradas, INT ( Fallas[Fecha_Hora_Cierre] ) = INT ( Fallas[Fecha_Hora_Falla] ) )",
              "        ),",
              "        COUNTROWS ( Cerradas )",
              "    )"
            ],
            "lineageTag": "99cb970e-ed47-4e77-9cf6-8eae3ab805aa",
            "formatString": "0%"
          },
          {
            "name": "Fallas Reincidentes 30d",
            "expression": [
              "COUNTROWS (",
              "    FILTER (",
              "        Fallas,",
              "        VAR EquipoActual = Fallas[ID_Maquina]",
              "        VAR TipoActual = Fallas[Tipo_Falla]",
              "        VAR FechaActual = Fallas[Fecha_Hora_Falla]",
              "        RETURN",
              "            NOT ISEMPTY (",
              "                FILTER (",
              "                    ALL ( Fallas ),",
              "                    Fallas[ID_Maquina] = EquipoActual",
              "                        && Fallas[Tipo_Falla] = TipoActual",
              "                        && Fallas[Fecha_Hora_Falla] < FechaActual",
              "                        && Fallas[Fecha_Hora_Falla] >= FechaActual - 30",
              "                )",
              "            )",
              "    )",
              ")"
            ],
            "lineageTag": "b139fd80-b433-49e6-abde-93ef5bbf4721",
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "MantencionMensual",
        "lineageTag": "0a351a84-006e-4857-a925-aef9f47bdc7b",
        "columns": [
          {
            "name": "ID_OT",
            "dataType": "string",
            "sourceColumn": "ID_OT",
            "lineageTag": "3714a5b1-1059-4f8a-9edf-532ad7a79ee4"
          },
          {
            "name": "ID_Maquina",
            "dataType": "string",
            "sourceColumn": "ID_Maquina",
            "lineageTag": "2777bb93-6602-4c50-90a3-af780c0d1061"
          },
          {
            "name": "Tarea",
            "dataType": "string",
            "sourceColumn": "Tarea",
            "lineageTag": "691d8612-a597-4347-921b-db16321c12cf"
          },
          {
            "name": "Frecuencia",
            "dataType": "string",
            "sourceColumn": "Frecuencia",
            "lineageTag": "7072cbec-6500-4e9a-a4be-fe49d386cc1b"
          },
          {
            "name": "Fecha_Programada",
            "dataType": "dateTime",
            "sourceColumn": "Fecha_Programada",
            "lineageTag": "b6a275a4-f30c-428a-8fd0-47b3108a2e91",
            "formatString": "dd-MM-yyyy"
          },
          {
            "name": "Fecha_Realizada",
            "dataType": "dateTime",
            "sourceColumn": "Fecha_Realizada",
            "lineageTag": "54aaf83d-2a5f-4530-a602-46feb835dfa9",
            "formatString": "dd-MM-yyyy"
          },
          {
            "name": "Estado",
            "dataType": "string",
            "sourceColumn": "Estado",
            "lineageTag": "726eead4-dab3-4bbf-a090-b2455ec0f7f2"
          },
          {
            "name": "Tecnico",
            "dataType": "string",
            "sourceColumn": "Tecnico",
            "lineageTag": "2e968686-6e55-4e1c-9e4e-b8944e81a36b"
          },
          {
            "name": "Duracion_Min",
            "dataType": "int64",
            "sourceColumn": "Duracion_Min",
            "lineageTag": "7a509817-9d99-4660-92a5-676d126def42",
            "summarizeBy": "none"
          },
          {
            "name": "Observaciones",
            "dataType": "string",
            "sourceColumn": "Observaciones",
            "lineageTag": "b69db053-2f22-4ca3-a0b1-eb652a896ea8"
          },
          {
            "name": "Estado Ejecucion",
            "dataType": "string",
            "type": "calculated",
            "lineageTag": "c2e124de-eb2f-4fb3-8531-f84fa0d8e604",
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    MantencionMensual[Estado] = \"Cancelada\", \"Cancelada\",",
              "    MantencionMensual[Estado] = \"Realizada\"",
              "        && NOT ISBLANK ( MantencionMensual[Fecha_Realizada] )",
              "        && MantencionMensual[Fecha_Realizada] <= MantencionMensual[Fecha_Programada], \"Realizada en fecha\",",
              "    MantencionMensual[Estado] = \"Realizada\", \"Realizada con atraso\",",
              "    MantencionMensual[Estado] = \"Reprogramada\"",
              "        && MantencionMensual[Fecha_Programada] < TODAY (), \"Atrasada\",",
              "    MantencionMensual[Estado] = \"Reprogramada\", \"Reprogramada\",",
              "    MantencionMensual[Fecha_Programada] < TODAY (), \"Atrasada\",",
              "    \"Programada\"",
              ")"
            ]
          }
        ],
        "partitions": [
          {
            "name": "MantencionMensual",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // DATOS DE EJEMPLO INCRUSTADOS — para conectar tu Google Sheet, reemplaza",
                "    // todo este código por power-query/conector-google-sheets/MantencionMensual.m",
                "    Datos = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"xVnLbts4FP0VwmsH0MMPprPqZDBFi/QBJ5hN0cWNxDjM0KSGkgwkf9NlF13lE/xjvaSsjkxTqusg9Eq+smSee++5j5N8/jz6eH2WRMnsLJqfRfFoPLp880/zYcHWvOSbJ0lyRnTNcijH5FYzqfBaZiAl0+arki1rzXPIx0TCmi0hsy89EM3KAkSuzEMF6M3XFau0KvGn3zNZ1iDw08+j566xYCD4I+SAny9AC1WSPzWsFZrn0WgsayG+jHfhJy38JDh86ho78JUsK5CPQP7afIfHAQ/S1oM0tAdp7BpdD97BmjMN5EpVJgFx0oN/0uKfhMafpK5xBIGmLfxpaPhx5Bpd+O/5smaCLDbf7et98Gf43dXra0/53kDFNHLPIMezN0+aZzDeemX9U+hAjRl+IAXevQFzM+OZUCRTq0Iwm3cP7tQ1jqHNvAWehAM+cY2BgMdpD3DaAk/DAZ+6Rhf4QuWaLxX5xOU25FM/8vMW+SQY8mTiGl3kfzPBC0ZeY4kyaW7EU3/QbXVY6NNw0OeuMUTzSQ/wuAU+C8eWuWsMx7ynQuOkhT4PF/Mtc8ejT1otNay8DG+e+KAIu2dZXeEzhElyXwuuXpH/EMTmiUCloTRvu16Zqr34sN133sqyYFn2s+OrnAthev0NSOPKA1lhfrVmeZ3hlZV/EMFXBWeP0IyB1nm/N5FrDPSbeU8WJi3e5MXxxrOuQX+B11TiFWYVj0M8JCG5YQQplCYFg3/NebmZhtmd2kuCeffdx0vP1CoEVHCr9Ar5lEGOFLWEAo3prDSzhGLt04KUvKzYCsgdz3HYIgMyP7HSyDWGVgV//7ThWVxcbXfmTlwzJVkT73GH7xWisEBtSFTJ/18SOg5jFVZcNAuEn0VJy/gFK7pVsbdi7j9FQJBoijPLYrgFUUHnzFzpvczMWx+T0D72j4n9XXoW9ZMv52WhJL/hwixolvYg9vuAoffF5ZvhZOIF+4lteUpLVu72M9BLaPtZTweIXWPYr74pct6CTV4SLPU239263++9r0i1+ZZJrDw8R/M10oqA4ZqwB297reOR7YbWo/QlPTp3jYERPvFVPT2dQKZ26/EkZLdb2Qd8uE+ljLdH7xgDc2QW+cN+KllM++pgly69YT+VHKa2bx5Pl1PpYGp35MP6jg93cAFM7WZ8PEGCC19ql97jIxxc8FK79R6oA3yIgwtd2qdcXLXVBzm8wEXIs2fQOLywpXY5fU6Mgwvapj0dKmjfykzUD9gvmcw5bsx28bGqduR6EkzENgPt6N4RTr1Su9EfDzSwIqX2L0pHT+uTSNFmSfBhPkCI9lL5FIKTWkV1sCe+BASQj/QsiZ6JMoBubDaaA3Xj4S0uhECk9p9evzECv/wA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"ID_OT\" = _t, #\"ID_Maquina\" = _t, #\"Tarea\" = _t, #\"Frecuencia\" = _t, #\"Fecha_Programada\" = _t, #\"Fecha_Realizada\" = _t, #\"Estado\" = _t, #\"Tecnico\" = _t, #\"Duracion_Min\" = _t, #\"Observaciones\" = _t]),",
                "    Tipos = Table.TransformColumnTypes(Datos, {{\"ID_OT\", type text}, {\"ID_Maquina\", type text}, {\"Tarea\", type text}, {\"Frecuencia\", type text}, {\"Fecha_Programada\", type date}, {\"Fecha_Realizada\", type date}, {\"Estado\", type text}, {\"Tecnico\", type text}, {\"Duracion_Min\", Int64.Type}, {\"Observaciones\", type text}}, \"es-CL\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "OT Programadas",
            "expression": [
              "CALCULATE ( COUNTROWS ( MantencionMensual ), MantencionMensual[Estado] <> \"Cancelada\" )"
            ],
            "lineageTag": "588290f8-39d5-48f5-93c0-83bab20f6716",
            "formatString": "#,0"
          },
          {
            "name": "OT Realizadas",
            "expression": [
              "CALCULATE ( COUNTROWS ( MantencionMensual ), MantencionMensual[Estado] = \"Realizada\" )"
            ],
            "lineageTag": "2b8e646f-b6ec-49aa-8c1b-27cbf10e5055",
            "formatString": "#,0"
          },
          {
            "name": "Cumplimiento PM %",
            "expression": [
              "DIVIDE ( [OT Realizadas], [OT Programadas] )"
            ],
            "lineageTag": "490cf7ce-a859-432c-a907-787a8b1d8474",
            "formatString": "0%"
          },
          {
            "name": "OT Realizadas En Fecha",
            "expression": [
              "COUNTROWS (",
              "    FILTER (",
              "        MantencionMensual,",
              "        MantencionMensual[Estado] = \"Realizada\"",
              "            && NOT ISBLANK ( MantencionMensual[Fecha_Realizada] )",
              "            && MantencionMensual[Fecha_Realizada] <= MantencionMensual[Fecha_Programada]",
              "    )",
              ")"
            ],
            "lineageTag": "0c49540e-72f6-45c3-80ea-c679fde21ee5",
            "formatString": "#,0"
          },
          {
            "name": "Puntualidad PM %",
            "expression": [
              "DIVIDE ( [OT Realizadas En Fecha], [OT Realizadas] )"
            ],
            "lineageTag": "a2c70759-86a3-4417-ab7e-530f9a1e04fd",
            "formatString": "0%"
          },
          {
            "name": "OT Atrasadas",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS (",
              "        FILTER (",
              "            MantencionMensual,",
              "            MantencionMensual[Estado] IN { \"Programada\", \"Reprogramada\" }",
              "                && MantencionMensual[Fecha_Programada] < TODAY ()",
              "        )",
              "    ),",
              "    REMOVEFILTERS ( Calendario )",
              ")"
            ],
            "lineageTag": "b04ab37a-0996-48e6-bf47-0a140b4c9b09",
            "formatString": "#,0"
          },
          {
            "name": "OT Proximas 7 Dias",
            "expression": [
              "CALCULATE (",
              "    COUNTROWS (",
              "        FILTER (",
              "            MantencionMensual,",
              "            MantencionMensual[Estado] IN { \"Programada\", \"Reprogramada\" }",
              "                && MantencionMensual[Fecha_Programada] >= TODAY ()",
              "                && MantencionMensual[Fecha_Programada] <= TODAY () + 7",
              "        )",
              "    ),",
              "    REMOVEFILTERS ( Calendario )",
              ")"
            ],
            "lineageTag": "18196486-a44b-4a6a-abb1-a546f55be3f5",
            "formatString": "#,0"
          },
          {
            "name": "Dias Atraso Promedio",
            "expression": [
              "AVERAGEX (",
              "    FILTER (",
              "        MantencionMensual,",
              "        MantencionMensual[Estado] = \"Realizada\"",
              "            && NOT ISBLANK ( MantencionMensual[Fecha_Realizada] )",
              "            && MantencionMensual[Fecha_Realizada] > MantencionMensual[Fecha_Programada]",
              "    ),",
              "    INT ( MantencionMensual[Fecha_Realizada] - MantencionMensual[Fecha_Programada] )",
              ")"
            ],
            "lineageTag": "3aaee0a2-e5e3-4ee2-885c-042a46a726aa",
            "formatString": "#,0.0"
          },
          {
            "name": "Horas PM Ejecutadas",
            "expression": [
              "DIVIDE (",
              "    CALCULATE ( SUM ( MantencionMensual[Duracion_Min] ), MantencionMensual[Estado] = \"Realizada\" ),",
              "    60",
              ")"
            ],
            "lineageTag": "5b7408ab-3ea4-4dc5-95cb-725e3ddffa52",
            "formatString": "#,0.0"
          }
        ]
      },
      {
        "name": "Pautas",
        "lineageTag": "64351958-4752-4959-9710-ef7482fe0ff6",
        "columns": [
          {
            "name": "ID_Pauta",
            "dataType": "string",
            "sourceColumn": "ID_Pauta",
            "lineageTag": "6fd2ed68-9078-4917-b049-3e1953caed8c"
          },
          {
            "name": "ID_Maquina",
            "dataType": "string",
            "sourceColumn": "ID_Maquina",
            "lineageTag": "ebaa739e-941c-4f44-bacc-a7767e7e2ec7"
          },
          {
            "name": "Frecuencia",
            "dataType": "string",
            "sourceColumn": "Frecuencia",
            "lineageTag": "6ea80024-11d8-4f28-8773-771671240e08"
          },
          {
            "name": "Tarea",
            "dataType": "string",
            "sourceColumn": "Tarea",
            "lineageTag": "542baa9b-47bf-4974-8302-71a11c321c10"
          },
          {
            "name": "Duracion_Min_Est",
            "dataType": "int64",
            "sourceColumn": "Duracion_Min_Est",
            "lineageTag": "9d43b5e7-3f6d-4c89-9941-0e0a9c75ed0d",
            "summarizeBy": "none"
          },
          {
            "name": "Link_Pauta",
            "dataType": "string",
            "sourceColumn": "Link_Pauta",
            "lineageTag": "f7748158-2dc2-40e5-b052-2771c503bef1",
            "dataCategory": "WebUrl"
          },
          {
            "name": "Observaciones",
            "dataType": "string",
            "sourceColumn": "Observaciones",
            "lineageTag": "84bd7baf-d86e-4c91-a88c-8ef6030ea996"
          }
        ],
        "partitions": [
          {
            "name": "Pautas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // DATOS DE EJEMPLO INCRUSTADOS — para conectar tu Google Sheet, reemplaza",
                "    // todo este código por power-query/conector-google-sheets/Pautas.m",
                "    Datos = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"5dtBc9pGFAfwr6LxWY6TtxI47kmDaeoO2Blwcmgmh0VasCZCS1eCqfNtfMwhp9x65Yv1rQR6aw2eDq5ppOVi7wBa6a+3+klCy6dPJ+9PB+8+nr5+c3p54p6UTWxcxlzFHBu9O/HnUkhnFWdLnrhOEs8XsfjKnUg4WcjTVCjn3lmopZgUr02VSGXm8MSJ0ziMpX4tX6pUYl9vXuOfuzxfZBdnZ5GKV+LVTMpZIl6Fcn426veH7wfBH8HobMGXOc9O+4P+7e3oqneulxsJMV8k/CtXjkhwM9IvzkIqJ+FO8WlHTnF1uNoI353yiYpx43LhiNS51Gs6+ewaWcdm1rGY85Qn+iUjnBLTRIS5VCLDgErgDojXP1L9ViSyGc9yUXxsKSKe4bKsMeGGZrihSHXhinUYEcrNdjflcqtS6qqK2VLFEY9cJ+UrMeNhsZDeB9mCJ1FR0gVX64e5yJXU2d82p7D9WmVFlqsifo/PJ+VwLLPrnOu/06qY7uMa41LhNnjIk3iiNvshWT9kQmGH4DUmdWCGDtKy3jcroe74MtkGLft93N8F5XSdCc+FWn/nerxnMe6SOTbNAYGdeucNCQ3kFdjuFZBXYJ1XQF7BsXkFhldwNF4BeQVH4xUjr5jtXjHyilnnFSOv2LF5xQyv2NF4xcgrdjReeeSVZ7tXHnnlWeeVR155x+aVZ3jlHY1XHnnlHY1XPnnl2+6VT1751nnlk1f+sXnlG175R+OVT175x+DVOLjdft9eNnd5hdu9zaMrKNOc48Fc5Am5mvGXESr4cHsz/C146WhjM9punjI8rtc/dDd1nTbDW7ckFm2p9G4BvxHBhmawJ2iqhqFrhHS3scxzTRiHicTa4vaJvCgfa0j9+rUC7lCoinn22CP8KEdja+pEelWhjEp5GjJMAzPlPuxoSKAJGYAUAcsUAVIErFIESBGwWBEwFAF7FQFSBNqqCCNFmGWKMFKEWaUII0WYxYowQxFmryKMFGFtVcQjRTzLFPFIEc8qRTxSxLNYEc9QxLNXEY8U8dqqiE+K+JYp4pMivlWK+KSIb7EivqGIb68iPinit1WRDinSsUyRDinSsUqRDinSsViRjqFIx15FOqRIp62KdEmRrmWKdEmRrlWKdEmRrsWKdA1FuvYq0iVFui1UpHdd/bKqbJqKjGQa8c28lAt9HMVJoqcyTHhaDsKpzGUoknJ6xr7luLq+7Y9GN4PBS4cZm2F2u0EbXncjx4ONR5uxmT5v4snBkg3NZATHVZotRFgdIjsKNce8SoloWU63+eXxJKPKF+yr6zeliv1aGXfNM0Ha57FI9Sntfpu2NuvkOfNIDhYqMDNtrSD35/xeFjOEdFasFZ613HrtMGjOJ4lQmFkk629hjqss5gjtjcmBYgJxAq3nBIgTsIsTIE7Adk7A4ARs4QSIE7CTk99vBturk7L5xD3OAoMUie/iSK0flkl5Q0DXyLgpOZ9KNed6FSserr8XV8p7jk7ciJvL4KXjjc14BjDLYrnqOAx5JNLyloYrhWNRibo2KfadGDtBPkObw2QcmhmfuOWhIrlV2HuqrV7PZtJkLeLbZpSxX6vjDmF4KGLswNj8egkzoa19jjKHSRWYofa9uzn/uRFGvfGWj7Jp8vFRqHhaHV9YjkUc8Q2WeMbWQ48nXJUzdBMHb0G/4FJ7jrRfRzfXVx/GL51obCbafUkSypTm1oePfmKg317hWS5OyvB6sL1uRK6hmYuU2J3LNXzXl1lFHfW6FzKLtxPLazk7zchZUGEWsKKCQMyFmssZjks9SLfJ/4rxT3F13JCKBWaQLQ9DvUBalqC6puCby5FQqLw48CJenJ2akAPICLDDCCAjwCYjgIwAm40AwwhotRFARkBLjegN3lVfkhbN/2BE8dglkmp/Jw7wO59NsLEZ7GdQcbhoQzPav2uB/zBZ8W2NVKmoPWgpnphtHrTo0nvNqWC/VsLDY3G4MIGZ5f/w4lBRgMgAq8gAIgMsIwOIDLCYDDDIgLaTAUQGtJwMRmQwq8hgRAazjAxGZDCLyWAGGaztZDAig7WSjM//AA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"ID_Pauta\" = _t, #\"ID_Maquina\" = _t, #\"Frecuencia\" = _t, #\"Tarea\" = _t, #\"Duracion_Min_Est\" = _t, #\"Link_Pauta\" = _t, #\"Observaciones\" = _t]),",
                "    Tipos = Table.TransformColumnTypes(Datos, {{\"ID_Pauta\", type text}, {\"ID_Maquina\", type text}, {\"Frecuencia\", type text}, {\"Tarea\", type text}, {\"Duracion_Min_Est\", Int64.Type}, {\"Link_Pauta\", type text}, {\"Observaciones\", type text}}, \"es-CL\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Calendario",
        "lineageTag": "84d643f5-8f3f-4322-b388-0a1622e2ed1c",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "type": "calculatedTableColumn",
            "sourceColumn": "[Fecha]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "d1dce275-1e63-485d-92db-e80bdfdd43d7",
            "isKey": true,
            "formatString": "dd-MM-yyyy"
          },
          {
            "name": "Anio",
            "dataType": "int64",
            "type": "calculatedTableColumn",
            "sourceColumn": "[Anio]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "4afa4924-6cc8-4786-a3bd-b8e18341af7c"
          },
          {
            "name": "MesNum",
            "dataType": "int64",
            "type": "calculatedTableColumn",
            "sourceColumn": "[MesNum]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "07cf247e-2caa-4732-bb50-6d96204e3aee"
          },
          {
            "name": "AnioMes",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "sourceColumn": "[AnioMes]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "12827cc1-3202-445a-8b77-0a8a2c50c96b"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "sourceColumn": "[Mes]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "f797172b-83c5-41d8-b8d5-a1115382ee62",
            "sortByColumn": "AnioMes"
          },
          {
            "name": "MesCorto",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "sourceColumn": "[MesCorto]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "ad869cd2-273a-4791-b716-f55bc8d03a30"
          },
          {
            "name": "Semana",
            "dataType": "int64",
            "type": "calculatedTableColumn",
            "sourceColumn": "[Semana]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "7a012b26-08b1-45b9-9b89-089a88df806f"
          },
          {
            "name": "Dia",
            "dataType": "int64",
            "type": "calculatedTableColumn",
            "sourceColumn": "[Dia]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "c0f67d7e-38ac-4b44-8310-28a13e9deae5"
          },
          {
            "name": "DiaSemanaNum",
            "dataType": "int64",
            "type": "calculatedTableColumn",
            "sourceColumn": "[DiaSemanaNum]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "33d9531c-598d-4f43-a88d-0092e4664ccf"
          },
          {
            "name": "DiaSemana",
            "dataType": "string",
            "type": "calculatedTableColumn",
            "sourceColumn": "[DiaSemana]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "8b9503a6-d2d4-4be9-997d-c8c5a3469f39",
            "sortByColumn": "DiaSemanaNum"
          },
          {
            "name": "EsFinDeSemana",
            "dataType": "boolean",
            "type": "calculatedTableColumn",
            "sourceColumn": "[EsFinDeSemana]",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "lineageTag": "614a0502-2732-402f-b407-16bf6e8c3802"
          }
        ],
        "partitions": [
          {
            "name": "Calendario",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "ADDCOLUMNS (",
                "    SELECTCOLUMNS ( CALENDARAUTO (), \"Fecha\", [Date] ),",
                "    \"Anio\", YEAR ( [Fecha] ),",
                "    \"MesNum\", MONTH ( [Fecha] ),",
                "    \"AnioMes\", FORMAT ( [Fecha], \"yyyy-MM\" ),",
                "    \"Mes\", FORMAT ( [Fecha], \"mmm yyyy\" ),",
                "    \"MesCorto\", FORMAT ( [Fecha], \"mmm\" ),",
                "    \"Semana\", WEEKNUM ( [Fecha], 2 ),",
                "    \"Dia\", DAY ( [Fecha] ),",
                "    \"DiaSemanaNum\", WEEKDAY ( [Fecha], 2 ),",
                "    \"DiaSemana\", FORMAT ( [Fecha], \"ddd\" ),",
                "    \"EsFinDeSemana\", WEEKDAY ( [Fecha], 2 ) > 5",
                ")"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "c72d020a-385e-4bcf-ae93-19a6a55e4cc9",
        "fromTable": "Bitacora",
        "fromColumn": "ID_Maquina",
        "toTable": "Maquinas",
        "toColumn": "ID_Maquina"
      },
      {
        "name": "924481da-4963-4523-9481-727989302b03",
        "fromTable": "Fallas",
        "fromColumn": "ID_Maquina",
        "toTable": "Maquinas",
        "toColumn": "ID_Maquina"
      },
      {
        "name": "8b050095-a416-4a4c-aa02-026fcbd71cc8",
        "fromTable": "MantencionMensual",
        "fromColumn": "ID_Maquina",
        "toTable": "Maquinas",
        "toColumn": "ID_Maquina"
      },
      {
        "name": "27fedc0d-8318-488b-b842-7059eb5448f8",
        "fromTable": "Pautas",
        "fromColumn": "ID_Maquina",
        "toTable": "Maquinas",
        "toColumn": "ID_Maquina"
      },
      {
        "name": "df0418d4-9a95-4e5a-abe2-18f7ad892709",
        "fromTable": "Bitacora",
        "fromColumn": "Fecha",
        "toTable": "Calendario",
        "toColumn": "Fecha"
      },
      {
        "name": "59e091f2-8813-4a22-9372-e80b7591e70f",
        "fromTable": "Fallas",
        "fromColumn": "Fecha",
        "toTable": "Calendario",
        "toColumn": "Fecha"
      },
      {
        "name": "4e50d8c0-d4b5-4817-afd7-952addb9f921",
        "fromTable": "MantencionMensual",
        "fromColumn": "Fecha_Programada",
        "toTable": "Calendario",
        "toColumn": "Fecha"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}