/* =====================================================================
   MATRIX · Núcleo conductual de los 22 Arcanos
   ---------------------------------------------------------------------
   Capa interpretativa que convierte los campos canónicos de la
   Biblioteca Maestra (recurso · Hipo · Híper · clave de integración)
   en cadenas conductuales observables:
     disparador → pensamiento → conducta → consecuencia (Hipo)
     disparador → necesidad de control → exceso → consecuencia (Híper)
   Cada texto debe seguir siendo coherente con el Hipo/Híper canónico
   del Arcano (01_ARCANOS). No define programas, nombres ni reglas:
   eso vive en matrix-data.js (generado desde la biblioteca).

   Campos:
   kern/obj/bloq/cuando/comp → piezas para frases causales entre Arcanos
   hipoC/hiperC              → versión breve de cada extremo
   nec/miedo                 → necesidad y miedo nucleares
   trig                      → disparadores concretos
   pens/cond/cons            → cadena Hipo
   necH/exc/consH            → cadena Híper
   ciclo/cicloTxt            → cómo un extremo alimenta al otro
   eq/integ                  → equilibrio observable / respuesta integrada
   sHipo/sHiper/prog/preg    → señales, indicadores y preguntas espejo
   acc                       → acción verificable ({amb} = ámbito de la zona)
   ===================================================================== */
window.MATRIX_CORE = {
1:{kern:"la duda sobre la propia capacidad",obj:"el impulso de empezar",bloq:"frenar",cuando:"cuando el arranque se posterga",comp:"querer controlarlo todo y forzar resultados",
hipoC:"dudas de tu capacidad y postergas",hiperC:"controlas y fuerzas resultados",
nec:"comprobar que tu voluntad produce efectos: decidir, empezar algo y ver que avanza gracias a ti",
miedo:"descubrir que no eres capaz, o que si sueltas el control las cosas se desordenan",
trig:["alguien pone en duda lo que puedes hacer o te pide pruebas","hay que empezar algo sin garantías de que saldrá bien","otra persona toma la iniciativa en algo que sentías tuyo","los resultados tardan más de lo que esperabas","te piden delegar algo que sabes hacer"],
pens:"«Todavía no es el momento; primero necesito tenerlo todo claro»",
cond:"postergas el inicio, pides opiniones antes de moverte y esperas una validación que no llega",
cons:"la idea pierde fuerza, otra persona la ejecuta o la haces tarde y sin energía, lo que confirma la duda del principio",
necH:"demostrar que puedes y que nada queda librado al azar",
exc:"tomas todas las decisiones, corriges a los demás y empujas resultados antes de tiempo",
consH:"los demás dejan de aportar o se resisten, y terminas cargando con todo sin apoyo",
ciclo:["dudas de tu capacidad","postergas","se acumulan presión y culpa por lo no hecho","tomas el control de golpe y fuerzas resultados","el desgaste o la resistencia ajena reavivan la duda"],
cicloTxt:"Cuanto más se posterga, más urgencia se acumula; esa urgencia se descarga luego en control y prisa. Cuando el control genera resistencia o agotamiento, la sensación de no ser capaz vuelve, y con ella la postergación.",
eq:["empiezas con un primer paso pequeño aunque no tengas todas las respuestas","pides opinión para mejorar, no para obtener permiso","defines qué parte te corresponde y dejas espacio a la iniciativa ajena","sostienes lo que empiezas hasta un punto de revisión acordado"],
integ:"Cuando vuelve la duda o alguien cuestiona tu capacidad, no esperas a tener certeza ni reaccionas imponiéndote: das un paso concreto dentro de las siguientes 24 horas y pides ayuda específica si la necesitas.",
sHipo:["tienes varios proyectos «para cuando sea el momento» que no empiezas","preguntas a varias personas antes de decidir algo que conoces bien","sientes alivio cuando otra persona decide por ti, y después frustración","te cuesta decir «yo lo hago» en voz alta"],
sHiper:["corriges o rehaces lo que otras personas ya hicieron","te irrita que las cosas no avancen a tu ritmo","te cuesta delegar incluso tareas menores","tomas decisiones que afectan a otros sin consultarlas"],
prog:["empiezas cosas sin esperar el momento perfecto","delegas y aceptas resultados distintos a los tuyos","terminas lo que inicias o lo cierras de forma consciente","pides ayuda concreta sin sentir que pierdes autoridad","tu iniciativa inspira a otros en lugar de reemplazarlos"],
preg:["¿Qué estoy esperando para empezar, y quién tendría que darme permiso?","¿En qué situaciones siento que si no lo hago yo, sale mal?","¿Qué empecé con fuerza y abandoné cuando no vi resultados rápidos?","¿Cuándo mi iniciativa deja sin espacio a otras personas?"],
acc:"Elige una acción postergada {amb}; hazla en las próximas 24 horas en su versión mínima y anota qué pensamiento apareció justo antes."},

2:{kern:"la desconfianza en la propia percepción",obj:"la intuición",bloq:"silenciar",cuando:"cuando lo que percibes queda sin decirse",comp:"encerrarse, acumular información y convertir el silencio en distancia",
hipoC:"desconfías de lo que percibes y te quedas en silencio",hiperC:"te encierras y acumulas información sin actuar",
nec:"confiar en lo que percibes y tener un espacio interno propio que otros respeten",
miedo:"equivocarte si expresas lo que intuyes, o quedar a la vista si muestras lo que guardas",
trig:["percibes algo que nadie más menciona","te piden una respuesta inmediata sin tiempo para procesar","alguien invalida lo que sientes con datos o lógica","hay una tensión en el ambiente que nadie nombra","tienes que exponer una opinión íntima en público"],
pens:"«Seguro es idea mía; mejor no digo nada»",
cond:"descartas tu impresión, te adaptas a la versión de los demás y te quedas en un papel pasivo",
cons:"lo que intuiste se confirma después, cuando ya es tarde, y crece la sensación de que tu voz no cuenta",
necH:"protegerte de la exposición y tener toda la información antes de moverte",
exc:"investigas, observas y guardas, pero no compartes ni decides; el silencio se vuelve distancia",
consH:"los demás te perciben distante, no saben qué necesitas y la intimidad se enfría",
ciclo:["percibes algo","dudas de tu percepción","callas y observas","acumulas información y te distancias","sin intercambio no hay contraste, y la duda crece"],
cicloTxt:"Callar para no equivocarse deja la percepción sin contraste; sin contraste, la duda crece y se compensa acumulando más información y más distancia, lo que refuerza el silencio.",
eq:["te das tiempo para procesar y luego comunicas lo que percibiste","contrastas tu intuición con hechos antes de concluir","dices «necesito pensarlo» y vuelves con una respuesta","eliges con quién abrir tu mundo interno"],
integ:"Cuando percibes algo que nadie nombra, no lo descartas ni te retiras: lo verificas con un dato o una pregunta y lo expresas en el momento adecuado, aunque sea con una frase breve.",
sHipo:["dices «no sé» cuando en realidad sí tienes una impresión","te enteras tarde de cosas que ya intuías","dejas que otros definan lo que tú sentías","te cuesta explicar por qué algo te incomoda"],
sHiper:["la gente dice que no sabe lo que piensas","investigas mucho y decides poco","te retiras cuando una conversación se vuelve íntima","guardas información que afecta a otras personas"],
prog:["compartes tus percepciones sin esperar certeza total","tus intuiciones, al contrastarlas, aciertan más a menudo","pides el tiempo que necesitas en vez de desaparecer","otras personas te buscan por tu criterio, no solo por tu escucha","eliges la reserva sin que se convierta en muro"],
preg:["¿Qué sé que no he dicho?","¿Cuándo uso el silencio para protegerme en lugar de para escuchar?","¿Qué percepción mía se confirmó después y no la sostuve?","¿Con quién puedo contrastar lo que intuyo?"],
acc:"Esta semana, anota una intuición {amb}, verifícala con un dato o una pregunta directa y compártela con una persona antes de siete días."},

3:{kern:"la búsqueda de valor a través de producir y cuidar",obj:"la creatividad y el disfrute",bloq:"sobrecargar",cuando:"cuando el disfrute propio se pospone",comp:"producir, cuidar o complacer de más para asegurar el afecto",
hipoC:"sientes que no creas ni disfrutas y te cuesta recibir",hiperC:"te dispersas, sobreproteges o produces para agradar",
nec:"hacer crecer algo propio y sentir que lo que das tiene valor y es recibido",
miedo:"perder valor a los ojos de otros si dejas de producir, cuidar o agradar",
trig:["alguien no reconoce lo que diste o creaste","te ofrecen ayuda o un regalo y te incomoda recibirlo","tienes tiempo libre sin nada que producir","una persona cercana te necesita justo cuando tienes un proyecto propio","critican tu trabajo creativo"],
pens:"«Lo mío no es tan importante; primero están los demás»",
cond:"dejas de crear, postergas lo que te da placer y te cuesta aceptar ayuda o regalos",
cons:"la energía creativa se apaga, aparece un cansancio sin causa clara y crece un vacío o un resentimiento silencioso",
necH:"asegurarte un lugar valorado siendo imprescindible",
exc:"abres muchos frentes, cuidas en exceso, das sin que te pidan y mides tu valor por lo que produces",
consH:"te dispersas, te agotas y los demás se acostumbran a recibir sin dar",
ciclo:["sientes que tu valor depende de lo que das","postergas tu propio disfrute","llenas el vacío produciendo o cuidando de más","llegan el agotamiento y la falta de reciprocidad","sientes que nadie te cuida, y vuelves a dar para merecer"],
cicloTxt:"Postergar el propio disfrute genera un vacío que se intenta llenar dando y produciendo más; el exceso agota y deja poca reciprocidad, lo que confirma la creencia de que hay que dar para merecer.",
eq:["creas algo propio con regularidad, sin que tenga que servir a nadie","recibes ayuda o elogios con un simple «gracias»","eliges qué proyectos nutrir y cuáles dejar","cuidas a otras personas sin descuidar tu descanso"],
integ:"Cuando alguien no valora lo que diste, no redoblas el esfuerzo ni te retiras con resentimiento: nombras lo que necesitas, decides cuánto más dar y sigues nutriendo lo que es tuyo.",
sHipo:["hace meses que no haces algo solo por placer","rechazas ayuda aunque la necesitas","sientes que tus ideas no valen la pena","descansar te genera culpa"],
sHiper:["tienes muchos proyectos abiertos y pocos terminados","ayudas antes de que te lo pidan","te duele mucho que no agradezcan lo que haces","te cuesta decir que no a quien te necesita"],
prog:["terminas los proyectos creativos que eliges","recibes sin sentir deuda","tu cuidado es elegido, no automático","descansas sin culpa","hay reciprocidad visible en tus vínculos"],
preg:["¿Qué hago para ganar valor ante otros y qué hago porque realmente lo deseo?","¿Qué me cuesta recibir?","¿Cuántos proyectos abrí por entusiasmo y cuántos sostengo?","¿A quién cuido para no mirar lo que yo necesito?"],
acc:"Durante siete días, dedica 30 minutos a crear o disfrutar algo {amb} que no tenga que servir a nadie, y acepta una ayuda que normalmente rechazarías."},

4:{kern:"la necesidad de control y estructura",obj:"la capacidad de decidir y ordenar",bloq:"rigidizar",cuando:"cuando nadie asume la decisión",comp:"endurecer las normas y controlar en exceso",
hipoC:"evitas decidir y cedes tu autoridad",hiperC:"rigidizas normas y controlas en exceso",
nec:"sentir que hay bases sólidas y que puedes sostenerlas",
miedo:"el caos, perder el control o no estar a la altura de la responsabilidad",
trig:["las reglas no están claras o alguien las incumple","te toca asumir una responsabilidad grande","alguien cuestiona tu autoridad o tu forma de organizar","un plan se desordena por factores externos","te piden flexibilidad en algo que consideras innegociable"],
pens:"«Que decida otra persona; si me equivoco, será mi culpa»",
cond:"evitas las decisiones de fondo, delegas tu autoridad o te sometes a estructuras ajenas aunque no te sirvan",
cons:"otros deciden por ti, la situación se desordena y crece la inseguridad frente a la responsabilidad",
necH:"recuperar la sensación de seguridad controlando el entorno",
exc:"impones reglas, supervisas en exceso y confundes liderazgo con imposición",
consH:"el entorno obedece por miedo o se rebela, y la estructura se vuelve más frágil de lo que parece",
ciclo:["sientes inseguridad ante la responsabilidad","evitas decidir","la situación se desordena","endureces normas para recuperar el control","la resistencia ajena aumenta la sensación de amenaza"],
cicloTxt:"Evitar decidir deja espacio al desorden; el desorden despierta miedo, y el miedo se compensa con rigidez. La rigidez provoca resistencia, que se vive como una nueva amenaza que controlar.",
eq:["pones reglas claras y explicas su razón","asumes decisiones y las revisas cuando cambian los datos","escuchas antes de fijar una estructura","proteges sin controlar cada detalle"],
integ:"Cuando algo se desordena o alguien cuestiona tu autoridad, no te retiras ni endureces las reglas de inmediato: preguntas qué falla, ajustas la estructura y sostienes la decisión con firmeza y escucha.",
sHipo:["dejas que otros definan cómo se hacen las cosas aunque no estés de acuerdo","sientes alivio cuando alguien toma el mando","te cuesta decir «esto no se negocia»","vives en estructuras que no elegiste"],
sHiper:["te molesta profundamente que alteren tus planes","revisas lo que otros hacen sin que te lo pidan","te han dicho que eres una persona rígida o controladora","te cuesta cambiar una decisión aunque veas que no funciona"],
prog:["las reglas que pones se entienden y se respetan sin tensión","decides a tiempo y rectificas sin sentir que pierdes fuerza","delegas con criterios claros","tu estructura da seguridad a otros sin asfixiarlos","toleras imprevistos sin perder el eje"],
preg:["¿Qué decisión estoy evitando asumir?","¿Dónde controlo por miedo y no porque sea necesario?","¿Qué estructura de mi vida no elegí y sigo sosteniendo?","¿Cómo reacciono cuando alguien cuestiona mi manera de organizar?"],
acc:"Define por escrito una regla o acuerdo {amb}: qué se hace, por qué y cuándo se revisa; compártelo con la persona involucrada y cúmplelo durante dos semanas."},

5:{kern:"la necesidad de tener la verdad correcta",obj:"los valores y el aprendizaje",bloq:"encorsetar",cuando:"cuando no hay un criterio propio claro",comp:"moralizar y exigir que otros sigan su verdad",
hipoC:"dudas de tus principios y evitas guiar",hiperC:"moralizas y exiges que otros sigan tu verdad",
nec:"que tu vida sea coherente con valores en los que crees y poder transmitir lo que aprendiste",
miedo:"equivocarte moralmente, no pertenecer o descubrir que lo que creías no era cierto",
trig:["alguien actúa en contra de lo que consideras correcto","te piden enseñar o aconsejar","una autoridad o tradición que respetabas te decepciona","tu familia o tu grupo esperan que sigas un camino determinado","tienes que decidir sin una regla clara"],
pens:"«¿Quién soy para opinar sobre esto?»",
cond:"sigues normas ajenas sin cuestionarlas o rechazas cualquier referencia, y evitas el papel de guía",
cons:"vives con valores prestados, te falta un rumbo interno y tu conocimiento no se transmite",
necH:"sentir seguridad teniendo la respuesta correcta",
exc:"das sermones, juzgas lo diferente y esperas que otros adopten tu forma de pensar",
consH:"las personas dejan de consultarte o se alejan, y te quedas con la razón pero sin vínculo",
ciclo:["no confías en tu propio criterio","sigues normas ajenas o las rechazas todas","la incoherencia genera malestar","te aferras a una verdad y la impones","el rechazo ajeno te hace dudar de nuevo"],
cicloTxt:"Sin criterio propio se adoptan normas ajenas; cuando esas normas fallan, la inseguridad se compensa aferrándose a una verdad rígida. La rigidez aleja a los demás y reabre la duda.",
eq:["decides desde valores que revisaste y elegiste","enseñas contando tu experiencia, no dictando reglas","escuchas otras visiones sin sentirlas como amenaza","reconoces referentes sin idealizarlos"],
integ:"Cuando alguien contradice lo que crees, no callas tu criterio ni intentas convencer a toda costa: explicas tu postura, preguntas por la del otro y decides qué conservar.",
sHipo:["cambias de opinión según con quién hablas","sientes que no tienes autoridad para aconsejar","sigues tradiciones familiares que no compartes","te incomoda que te pidan una opinión de fondo"],
sHiper:["corriges moralmente a otras personas","te irrita que alguien piense muy distinto","das consejos que nadie pidió","te cuesta admitir que cambiaste de idea"],
prog:["tus decisiones siguen valores que puedes explicar","enseñas y aprendes al mismo tiempo","aceptas diferencias sin tener que convencer","revisas creencias heredadas sin culpa","te buscan como guía sin sentirse juzgados"],
preg:["¿Qué valores sigo por costumbre y cuáles elegí?","¿Cuándo uso lo que sé para acercarme y cuándo para tener razón?","¿Qué aprendí que podría enseñar?","¿Qué creencia familiar me cuesta cuestionar?"],
acc:"Escribe tres valores que guían tus decisiones {amb}; revisa una decisión reciente frente a ellos y comparte lo aprendido con alguien sin darle consejos."},

6:{kern:"la necesidad de aprobación",obj:"la elección",bloq:"dificultar",cuando:"cuando la decisión se posterga",comp:"idealizar el vínculo y depender de la aprobación ajena",
hipoC:"temes elegir y evitas el compromiso",hiperC:"dependes de la aprobación y te pierdes en el vínculo",
nec:"elegir en coherencia con lo que valoras y sentir que perteneces a un vínculo recíproco",
miedo:"elegir mal, decepcionar a alguien o quedar fuera del vínculo",
trig:["tienes que elegir entre dos opciones que te importan","alguien importante no está de acuerdo contigo","hay que poner un límite en una relación","sientes que podrías decepcionar a otra persona","un vínculo se enfría sin explicación"],
pens:"«Si elijo mal lo pierdo todo; mejor dejo las opciones abiertas»",
cond:"postergas decisiones, evitas definir el vínculo y te desconectas de lo que realmente necesitas",
cons:"las oportunidades se deciden solas, las relaciones quedan en ambigüedad y crece la sensación de no estar en ningún lado",
necH:"asegurarte de que te elijan y de no quedar fuera",
exc:"te adaptas a lo que el otro quiere, idealizas la relación y buscas aprobación constante",
consH:"pierdes identidad dentro del vínculo, aparece resentimiento y la relación se vuelve desigual",
ciclo:["temes elegir mal","postergas o dejas que otros elijan","la ambigüedad genera inseguridad","te adaptas o idealizas para asegurar el vínculo","al perderte en el otro, vuelve el miedo a elegir"],
cicloTxt:"No elegir para no equivocarse deja el vínculo en ambigüedad; la inseguridad se compensa adaptándose e idealizando. Al perder identidad, cualquier elección posterior se vuelve más amenazante.",
eq:["eliges aunque haya renuncia y sostienes la elección","expresas desacuerdo sin romper el vínculo","pides lo que necesitas en la relación","te relacionas desde tus valores, no desde el miedo a quedar fuera"],
integ:"Cuando alguien importante no aprueba tu decisión, no la abandonas para complacer ni cortas el vínculo: escuchas, explicas tu elección y aceptas que el otro pueda no estar de acuerdo.",
sHipo:["tienes decisiones importantes «en pausa» desde hace tiempo","preguntas «¿tú qué harías?» antes de decidir algo tuyo","evitas conversaciones que definan una relación","te cuesta saber qué quieres en un vínculo"],
sHiper:["cambias gustos o planes según tu pareja o tu grupo","te angustia que alguien esté en desacuerdo contigo","idealizas a las personas al principio y luego te decepcionas","dices que sí cuando quieres decir que no"],
prog:["decides en plazos razonables y sostienes lo elegido","expresas desacuerdos manteniendo el afecto","conservas gustos, amistades y proyectos propios dentro de la pareja","eliges vínculos recíprocos","la aprobación ajena importa, pero no decide por ti"],
preg:["¿Qué elección estoy postergando para no perder alternativas?","¿Qué dejo de decir para que me sigan queriendo?","¿Qué parte de mí desaparece cuando estoy en pareja?","¿A quién elijo por miedo a quedarme sin nadie?"],
acc:"Toma una decisión pendiente {amb} en un plazo de 72 horas, escribe a qué renuncias al elegirla y comunícala sin pedir aprobación."},

7:{kern:"la urgencia de avanzar",obj:"la dirección",bloq:"desviar",cuando:"cuando no hay un rumbo claro",comp:"acelerar, competir y querer imponerse para no perder el control",
hipoC:"pierdes el rumbo y abandonas ante los obstáculos",hiperC:"aceleras y compites de más",
nec:"sentir que avanzas hacia una meta clara y que tu esfuerzo te lleva a algún lugar",
miedo:"quedarte sin avanzar, perder o que otra persona llegue antes",
trig:["un proyecto se estanca o se retrasa","alguien avanza más rápido que tú","aparece un obstáculo inesperado","te piden esperar o bajar el ritmo","no tienes una meta definida"],
pens:"«Para qué seguir si no llego a ninguna parte»",
cond:"abandonas ante el primer obstáculo, cambias de meta o te quedas sin moverte por miedo a fallar",
cons:"acumulas proyectos a medias y crece la sensación de estancamiento",
necH:"no perder el control ni la posición",
exc:"aceleras, compites incluso donde no hace falta y atropellas procesos o personas",
consH:"te agotas, generas conflictos y llegas a la meta sin disfrutarla ni poder sostenerla",
ciclo:["no hay un rumbo claro","te detienes o cambias de meta","sientes que te quedas atrás","aceleras y compites para recuperar terreno","el agotamiento o el conflicto te frenan otra vez"],
cicloTxt:"Sin dirección clara, cada obstáculo detiene; la sensación de quedarse atrás se compensa con aceleración y competencia, que agotan y vuelven a frenar el avance.",
eq:["defines metas concretas con etapas","avanzas a un ritmo que puedes sostener","ajustas el rumbo sin abandonar","colaboras en lugar de competir cuando conviene"],
integ:"Cuando algo se estanca o alguien te adelanta, no abandonas ni aceleras a ciegas: revisas la meta, eliges el siguiente paso y mantienes un ritmo sostenible.",
sHipo:["tienes varios proyectos iniciados y abandonados","te desanimas rápido ante un obstáculo","cambias de objetivo con frecuencia","te cuesta decir hacia dónde vas"],
sHiper:["vives con prisa aunque no haga falta","te comparas y compites constantemente","te irrita esperar","descansar te genera culpa"],
prog:["terminas etapas y las celebras","superas obstáculos sin cambiar de meta","sabes cuándo frenar","compites solo cuando suma","tu ritmo se sostiene en el tiempo"],
preg:["¿Hacia dónde voy realmente?","¿Contra quién estoy compitiendo, y para qué?","¿Qué abandoné cuando apareció el primer obstáculo?","¿Qué pasaría si avanzara a menor velocidad sin detenerme?"],
acc:"Elige una meta {amb}, divídela en tres etapas con fecha y cumple la primera esta semana sin agregar metas nuevas."},

8:{kern:"la exigencia de corrección",obj:"el criterio para decidir",bloq:"paralizar",cuando:"cuando evitar decidir parece más seguro",comp:"juzgar con rigidez y exigir perfección",
hipoC:"evitas decidir y relativizas límites",hiperC:"juzgas con rigidez y exiges perfección",
nec:"que haya equilibrio, reciprocidad y coherencia entre lo que se da y lo que se recibe",
miedo:"la injusticia, equivocarte o tener que asumir consecuencias",
trig:["percibes una injusticia o un trato desigual","alguien incumple un acuerdo","tienes que tomar una decisión con consecuencias","cometes un error visible","te piden flexibilidad con una regla"],
pens:"«No me corresponde decidir; mejor no me meto»",
cond:"evitas tomar posición, relativizas límites y postergas decisiones por miedo a las consecuencias",
cons:"los desequilibrios crecen, otros deciden por ti y acumulas malestar por lo que consideras injusto",
necH:"sentir seguridad a través de las reglas y de tener razón",
exc:"juzgas con dureza, llevas la cuenta de lo que se da y se recibe y reduces lo complejo a correcto o incorrecto",
consH:"los vínculos se tensan, te exiges hasta agotarte y los demás se sienten evaluados",
ciclo:["evitas decidir por miedo a equivocarte","el desequilibrio crece","sientes una injusticia acumulada","juzgas y exiges con rigidez","la tensión que generas te hace temer más las consecuencias"],
cicloTxt:"Evitar decidir permite que el desequilibrio crezca; la injusticia acumulada se descarga en un juicio rígido, que tensa el entorno y aumenta el miedo a las consecuencias de cualquier decisión.",
eq:["decides con criterios explícitos y asumes las consecuencias","corriges errores sin castigarte","pones límites proporcionales","consideras el contexto humano antes de juzgar"],
integ:"Cuando alguien incumple un acuerdo o cometes un error, no lo dejas pasar ni reaccionas con condena: nombras el hecho, propones una reparación concreta y ajustas el acuerdo.",
sHipo:["dejas pasar situaciones que te parecen injustas","te cuesta tomar postura en los conflictos","postergas decisiones con consecuencias","relativizas límites para evitar discusiones"],
sHiper:["llevas la cuenta de lo que das y lo que recibes","te cuesta perdonar errores propios o ajenos","ves las situaciones en blanco y negro","te exiges perfección en los detalles"],
prog:["decides a tiempo y asumes lo que implica","reparas en lugar de castigar","tus límites son claros y proporcionales","reconoces los grises sin perder el criterio","tus acuerdos se cumplen con menos tensión"],
preg:["¿Qué decisión evito por miedo a las consecuencias?","¿Dónde llevo la cuenta en lugar de conversar?","¿Qué error propio sigo sin perdonarme?","¿Qué acuerdo necesita revisarse?"],
acc:"Identifica un desequilibrio {amb}, propón a la otra persona un acuerdo concreto con fecha de revisión y registra si se cumple."},

9:{kern:"la tendencia al aislamiento",obj:"la comprensión profunda",bloq:"aislar",cuando:"cuando la reflexión no se comparte",comp:"retirarse, sobreanalizar y convertir la independencia en distancia",
hipoC:"evitas estar a solas con tus preguntas y buscas respuestas afuera",hiperC:"te aíslas y sobreanalizas",
nec:"tiempo propio para comprender y la libertad de llegar a tus propias conclusiones",
miedo:"sentir que invaden tu espacio, o quedar a solas con tus preguntas sin respuesta",
trig:["hay mucho ruido, presión o demandas externas","te piden respuestas rápidas","alguien invade tu espacio o tu tiempo","te enfrentas a una pregunta existencial","un vínculo te pide más cercanía emocional"],
pens:"«Alguien más sabrá la respuesta»",
cond:"buscas respuestas en otros sin escucharte, llenas el silencio con actividad y evitas estar a solas",
cons:"acumulas opiniones contradictorias y pierdes contacto con tu propio criterio",
necH:"protegerte del exceso de contacto y conservar el control de tu mundo interno",
exc:"te aíslas, analizas sin cesar y mantienes a los demás a distancia",
consH:"te quedas sin intercambio, los vínculos se enfrían y lo que comprendes no llega a nadie",
ciclo:["evitas estar a solas con tus preguntas","buscas respuestas afuera","te saturas de opiniones","te retiras y te aíslas","la soledad prolongada vuelve incómodas las preguntas"],
cicloTxt:"Evitar el silencio lleva a buscar respuestas afuera; la saturación empuja a un retiro total, y el aislamiento prolongado vuelve más difícil sostener las propias preguntas.",
eq:["te retiras para pensar y vuelves con una conclusión","compartes lo que comprendes","pones límites a tu tiempo sin cortar vínculos","aprendes de la experiencia y la transmites"],
integ:"Cuando la presión externa sube, no desapareces ni te llenas de opiniones: pides un tiempo concreto para pensar y vuelves a comunicar lo que decidiste.",
sHipo:["no toleras el silencio","consultas a muchas personas antes de cada decisión","te cuesta pasar tiempo a solas","sigues consejos que no sientes tuyos"],
sHiper:["pasas largos periodos sin contacto real con nadie","analizas decisiones durante meses","te han dicho que pareces distante","te cuesta pedir ayuda"],
prog:["tus retiros tienen principio y final","compartes lo que aprendes","tu autonomía convive con vínculos cercanos","te consultan por tu profundidad","decides después de reflexionar, sin postergar indefinidamente"],
preg:["¿De qué me protejo cuando me aíslo?","¿Qué comprendí que aún no compartí?","¿A quién le pregunto para no escucharme?","¿Cuánto tiempo de reflexión necesito realmente?"],
acc:"Reserva una hora semanal sin pantallas para reflexionar sobre una pregunta {amb} y, al terminar, comparte tu conclusión con una persona de confianza."},

10:{kern:"la dependencia de la novedad o del azar",obj:"la lectura de los ciclos",bloq:"desordenar",cuando:"cuando nada llega a consolidarse",comp:"cambiar de rumbo constantemente y depender de la suerte",
hipoC:"te resistes al cambio y dejas pasar oportunidades",hiperC:"vives de la novedad y cambias sin consolidar",
nec:"sentir movimiento, oportunidades y que la vida no se estanca",
miedo:"el estancamiento o, al contrario, perder el control frente a lo que cambia",
trig:["una etapa termina sin que lo decidas","aparece una oportunidad inesperada","la rutina se prolonga","algo que funcionaba deja de hacerlo","tienes que comprometerte a largo plazo"],
pens:"«Nada va a cambiar, así que para qué intentarlo»",
cond:"te aferras a lo conocido, ignoras señales de cambio y dejas pasar oportunidades",
cons:"el cambio llega de todos modos, pero sin preparación, y se vive como algo que te pasa",
necH:"escapar del estancamiento sintiendo movimiento constante",
exc:"buscas novedad permanente, cambias de rumbo sin consolidar o lo dejas todo a la suerte",
consH:"nada llega a madurar, los resultados son inestables y crece la sensación de empezar siempre de cero",
ciclo:["te resistes al cambio","las señales se acumulan","el cambio llega de golpe","buscas novedad para escapar de la sensación de encierro","sin consolidar nada, el siguiente cambio vuelve a asustar"],
cicloTxt:"Resistir el cambio hace que llegue de golpe; para no volver a sentir encierro se busca novedad constante, que impide consolidar y vuelve temible el próximo cambio.",
eq:["detectas cuándo una etapa termina y te preparas","aprovechas oportunidades con criterio","sostienes decisiones más allá del entusiasmo inicial","aceptas los ciclos sin sentirte a merced de ellos"],
integ:"Cuando algo cambia sin tu permiso, no te aferras ni saltas a otra cosa: revisas qué termina, qué oportunidad trae y qué vale la pena sostener.",
sHipo:["sigues por costumbre en situaciones que ya no te funcionan","dices «así son las cosas»","rechazas propuestas nuevas sin evaluarlas","sientes que la vida te pasa por encima"],
sHiper:["te aburres rápido de proyectos o relaciones","cambias de plan con frecuencia","esperas que la suerte lo resuelva","te cuesta sostener compromisos largos"],
prog:["cierras etapas con conciencia","consolidas algo antes de empezar lo siguiente","aprovechas oportunidades sin dispersarte","tu estabilidad no depende de que nada cambie","planificas teniendo en cuenta los ciclos"],
preg:["¿Qué etapa de mi vida ya terminó y sigo sosteniendo?","¿Qué empiezo por novedad y abandono por aburrimiento?","¿Qué oportunidad dejé pasar por miedo al cambio?","¿Qué necesito consolidar antes de cambiar?"],
acc:"Haz una lista de lo que está cambiando {amb}; elige una cosa para cerrar y otra para sostener tres meses sin modificarla."},

11:{kern:"la intensidad sin regular",obj:"la fuerza vital",bloq:"sofocar",cuando:"cuando el deseo o el enojo se reprimen",comp:"intimidar, competir por poder o descargar la intensidad sin regulación",
hipoC:"te quedas sin fuerza y reprimes lo que necesitas",hiperC:"intimidas o expresas la intensidad sin regular",
nec:"sentir energía y poder sostener lo que deseas con firmeza",
miedo:"la debilidad, quedar a merced de otros o perder el control de tu propia intensidad",
trig:["alguien te presiona o intenta dominarte","tienes que defender lo que necesitas","una frustración se acumula en el cuerpo","te enfrentas a una situación de poder","te piden calma cuando estás en plena tensión"],
pens:"«No vale la pena pelear por esto»",
cond:"reprimes deseos y enojo, cedes para evitar el conflicto y no defiendes lo que necesitas",
cons:"la energía se estanca, aparecen cansancio o irritabilidad y la frustración se acumula",
necH:"recuperar el control y no volver a sentir debilidad",
exc:"te impones, compites por poder o descargas la intensidad de golpe",
consH:"los demás se sienten intimidados, surgen conflictos y después aparecen culpa o desgaste",
ciclo:["reprimes lo que necesitas","la frustración se acumula","la tensión se vuelve insoportable","la intensidad explota o se impone","la culpa te lleva a reprimirte de nuevo"],
cicloTxt:"Reprimir para evitar el conflicto acumula tensión; cuando desborda, la intensidad sale sin regulación. La culpa posterior lleva a reprimir otra vez, y el ciclo se cierra.",
eq:["expresas lo que necesitas con firmeza serena","canalizas la energía en actividad física o en proyectos","defiendes límites sin agredir","reconoces tu deseo sin avergonzarte"],
integ:"Cuando alguien te presiona, no cedes ni explotas: haces una pausa física, dices con calma lo que necesitas y sostienes tu posición sin elevar el tono.",
sHipo:["cedes para evitar discusiones y luego te sientes mal","tienes cansancio sin una causa física clara","te cuesta nombrar lo que deseas","acumulas enojo en silencio"],
sHiper:["tus reacciones asustan a otras personas","sientes que siempre tienes que ganar","te cuesta frenar cuando estás en tensión","te arrepientes de cómo dijiste algo"],
prog:["expresas desacuerdo sin explotar","tu energía se sostiene a lo largo del día","otras personas se sienten seguras con tu fuerza","canalizas la frustración antes de que desborde","defiendes lo que necesitas con respeto"],
preg:["¿Qué deseo o qué enojo estoy reprimiendo?","¿Cuándo uso la intensidad para no sentirme vulnerable?","¿Qué necesito defender y no estoy defendiendo?","¿Dónde descargo la tensión acumulada?"],
acc:"Esta semana, ante la próxima tensión {amb}, respira diez segundos antes de responder y expresa lo que necesitas en una sola frase, sin justificarte ni atacar."},

12:{kern:"la tendencia a esperar y sacrificarse",obj:"la capacidad de pausar y mirar desde otro ángulo",bloq:"detener",cuando:"cuando la espera se prolonga sin decisión",comp:"inmovilizarse o sacrificarse en exceso",
hipoC:"rechazas la pausa y vives la espera como fracaso",hiperC:"te inmovilizas o te sacrificas en exceso",
nec:"sentir que tu entrega tiene sentido y poder cambiar de perspectiva sin presión",
miedo:"depender de otros, fracasar o que tu sacrificio no sea reconocido",
trig:["una situación no avanza por más que lo intentes","alguien necesita que renuncies a algo tuyo","te obligan a esperar sin plazo","sientes que das más de lo que recibes","tienes que pedir ayuda"],
pens:"«Detenerme es fracasar; tengo que seguir aunque no funcione»",
cond:"fuerzas situaciones que requieren pausa, no aceptas depender de nadie y te niegas a mirar desde otro ángulo",
cons:"insistes en lo que no funciona y el desgaste aumenta sin resultados",
necH:"darle sentido a la espera o al sacrificio",
exc:"te quedas indefinidamente en situaciones estancadas, renuncias a lo tuyo por otros y postergas decisiones",
consH:"aparece resentimiento, pierdes oportunidades y sientes que la vida está en suspenso",
ciclo:["te niegas a hacer una pausa","insistes hasta agotarte","el agotamiento te obliga a detenerte","te quedas en suspenso o te sacrificas","la espera sin decisión se vive como fracaso y vuelves a forzar"],
cicloTxt:"Rechazar la pausa lleva a forzar hasta el agotamiento; cuando la detención llega obligada, se transforma en inmovilidad o sacrificio, que se vive como fracaso y empuja de nuevo a forzar.",
eq:["haces pausas elegidas y con plazo","cambias de perspectiva antes de decidir","das sin renunciar a lo esencial","pides ayuda sin sentirte en deuda"],
integ:"Cuando algo se estanca, no fuerzas ni te resignas: te das un plazo concreto de pausa, buscas otra mirada sobre el problema y, al vencer el plazo, decides.",
sHipo:["te cuesta parar incluso con agotamiento","sientes que pedir ayuda es debilidad","insistes en caminos que no funcionan","la espera te angustia"],
sHiper:["llevas mucho tiempo esperando que algo cambie","renuncias a planes propios por otras personas","sientes que las circunstancias deciden por ti","postergas decisiones importantes"],
prog:["tus pausas terminan en decisiones","das sin resentimiento","ves alternativas donde antes veías callejones sin salida","pides ayuda cuando la necesitas","recuperas proyectos propios que habías postergado"],
preg:["¿Qué estoy esperando que cambie sin hacer nada?","¿A qué renuncié por otros y hoy me pesa?","¿Qué vería si mirara esta situación desde otro lugar?","¿Cuándo mi pausa es fértil y cuándo es miedo?"],
acc:"Elige una situación estancada {amb}, fija una fecha límite de pausa (máximo 14 días) y escribe tres perspectivas distintas antes de decidir cuando venza el plazo."},

13:{kern:"la dificultad para cerrar",obj:"la transformación",bloq:"estancar",cuando:"cuando se sostiene lo que ya terminó",comp:"romper de golpe y reiniciar sin comprender",
hipoC:"te aferras a lo que ya terminó",hiperC:"rompes de golpe o vives en reinicios",
nec:"renovarte y dejar ir lo que ya cumplió su ciclo",
miedo:"la pérdida y el vacío que queda después de un final",
trig:["una relación, un trabajo o una etapa llegan a su fin","alguien se va o cambia","algo que funcionaba deja de funcionar","te piden soltar algo importante","sientes que nada cambia"],
pens:"«Todavía puede funcionar; no quiero perderlo»",
cond:"sostienes relaciones, trabajos o hábitos que ya terminaron y evitas los duelos",
cons:"vives mirando al pasado, te cuesta avanzar y el cierre llega más tarde y más doloroso",
necH:"evitar el dolor de perder cortando antes",
exc:"rompes de golpe, eliminas antes de comprender o reinicias constantemente",
consH:"no integras lo aprendido, dañas vínculos y repites el mismo patrón en cada comienzo",
ciclo:["te aferras a lo que terminó","el malestar crece","el cierre llega forzado o abrupto","rompes todo y empiezas de cero","sin integrar lo aprendido, lo nuevo repite lo viejo"],
cicloTxt:"Aferrarse retrasa el final hasta que se impone de golpe; para no volver a sufrir, se corta rápido y se reinicia. Sin duelo ni aprendizaje, el nuevo comienzo reproduce el mismo patrón.",
eq:["reconoces cuándo algo terminó","cierras conversando y agradeciendo","haces el duelo necesario","conservas el aprendizaje antes de empezar de nuevo"],
integ:"Cuando algo llega a su fin, no lo sostienes artificialmente ni lo destruyes: nombras el final, rescatas lo que aprendiste y dejas un espacio antes de reemplazarlo.",
sHipo:["hablas mucho del pasado","sigues en algo que ya no te hace bien por miedo al vacío","guardas objetos o vínculos que te pesan","evitas las despedidas"],
sHiper:["cortas relaciones o trabajos de golpe","empiezas de cero con frecuencia","te cuesta volver a algo que dejaste","destruyes lo que te decepciona"],
prog:["cierras etapas con conciencia","puedes nombrar lo que aprendiste de cada final","te despides sin romper","tus nuevos comienzos no repiten los viejos errores","toleras el vacío entre una etapa y otra"],
preg:["¿Qué terminó y sigo sosteniendo?","¿Qué corté sin comprender por qué?","¿Qué aprendí del último final?","¿Qué duelo tengo pendiente?"],
acc:"Escribe una carta de cierre, sin enviarla, a algo que terminó {amb}: qué agradeces, qué aprendiste y qué dejas ir; luego haz un gesto concreto de cierre."},

14:{kern:"la evitación del conflicto",obj:"el equilibrio",bloq:"diluir",cuando:"cuando se evita tomar postura",comp:"acomodarse demasiado y usar la calma para no confrontar",
hipoC:"pierdes tu centro y tu ritmo",hiperC:"evitas el conflicto y te acomodas demasiado",
nec:"armonía, un ritmo propio y sentir que las partes de tu vida encajan",
miedo:"el conflicto, la ruptura o perder la paz",
trig:["dos personas cercanas están en conflicto","tienes que tomar partido","exigencias externas alteran tu ritmo","hay tensión en un vínculo","te sientes en medio de dos opciones"],
pens:"«No encuentro mi lugar; todo me desborda»",
cond:"pierdes el ritmo, te fragmentas entre demandas y oscilas entre extremos",
cons:"vives con sensación de dispersión y cansancio, sin un centro estable",
necH:"mantener la paz a cualquier precio",
exc:"evitas el conflicto, te acomodas a todos y usas la calma para no tomar postura",
consH:"los problemas quedan sin resolver, otros deciden por ti y acumulas malestar en silencio",
ciclo:["pierdes tu centro","oscilas entre extremos","el desorden genera tensión","buscas la paz evitando todo conflicto","los temas sin resolver vuelven a desestabilizarte"],
cicloTxt:"Sin centro se oscila; la tensión de oscilar se compensa buscando paz a toda costa. Pero evitar conflictos deja temas abiertos que vuelven a sacarte de tu eje.",
eq:["mantienes un ritmo que puedes sostener","medias sin renunciar a tu opinión","integras necesidades distintas con acuerdos claros","regulas sin reprimir"],
integ:"Cuando surge un conflicto, no te fragmentas ni lo evitas: escuchas a las partes, dices tu postura con calma y propones un acuerdo concreto.",
sHipo:["sientes dispersión entre demasiadas cosas","no encuentras tu propio ritmo","pasas de un extremo al otro","te cuesta sostener hábitos"],
sHiper:["dices «me da igual» cuando no es así","evitas conversaciones difíciles","te adaptas a todo el mundo","te cuesta mostrar enojo"],
prog:["tomas postura manteniendo la calma","tus hábitos se sostienen","medias con acuerdos que se cumplen","tu paz no depende de evitar conflictos","integras áreas de tu vida que antes competían"],
preg:["¿Qué conflicto estoy evitando?","¿Dónde digo «me da igual» para no molestar?","¿Qué ritmo necesito realmente?","¿Qué partes de mi vida necesito integrar?"],
acc:"Elige una conversación que vienes evitando {amb}; prepárala con tres frases (qué pasa, qué necesitas, qué propones) y tenla esta semana."},

15:{kern:"la necesidad de retener",obj:"el deseo",bloq:"atrapar",cuando:"cuando el deseo no se reconoce",comp:"transformar el deseo en apego o necesidad de control",
hipoC:"temes tu deseo y rechazas el placer",hiperC:"caes en apego, control o compulsión",
nec:"reconocer y materializar lo que deseas: placer, poder, dinero, intensidad",
miedo:"perder lo que tienes, quedarte sin poder o descubrir la fuerza de tu propio deseo",
trig:["deseas algo con mucha intensidad","sientes que puedes perder a alguien o algo","tienes acceso a dinero, poder o placer","alguien te seduce o intenta manipularte","sientes carencia"],
pens:"«Desear tanto está mal; mejor no pido nada»",
cond:"niegas tus deseos, rechazas el placer o el dinero y te desconectas de tu poder material",
cons:"el deseo reprimido vuelve como tentación, frustración o dificultad para generar recursos",
necH:"asegurar lo que deseas y no perderlo",
exc:"te apegas, controlas, caes en compulsiones o confundes intensidad con profundidad",
consH:"quedas atado a vínculos, hábitos o dinero que te dominan, y surgen celos o dependencia",
ciclo:["niegas el deseo","el deseo reprimido crece","aparecen la tentación o la carencia","te apegas o controlas para no perder","la dependencia genera culpa y vuelves a negar el deseo"],
cicloTxt:"Negar el deseo lo intensifica; cuando irrumpe, se vive con urgencia y miedo a perderlo, lo que genera apego y control. La culpa por el exceso lleva a negar el deseo otra vez.",
eq:["reconoces lo que deseas sin avergonzarte","disfrutas sin depender","negocias con claridad","usas tu poder con ética"],
integ:"Cuando sientes miedo a perder algo o a alguien, no te aferras ni lo niegas: nombras el deseo, revisas qué te da seguridad real y eliges con libertad.",
sHipo:["te incomoda hablar de dinero o de sexualidad","rechazas placeres por culpa","te cuesta cobrar lo que vale tu trabajo","reprimes deseos que luego estallan"],
sHiper:["revisas o controlas a tu pareja","te cuesta dejar hábitos que sabes que te dañan","gastas o consumes de forma compulsiva","sientes celos intensos"],
prog:["hablas de dinero y deseo con naturalidad","disfrutas sin culpa ni exceso","dejas ir sin controlar","cobras con justicia","tus vínculos son intensos sin ser posesivos"],
preg:["¿Qué deseo niego?","¿Qué vínculo, hábito o bien me cuesta soltar?","¿Qué controlo por miedo a perderlo?","¿Cómo uso mi poder de influencia?"],
acc:"Escribe qué deseas de verdad {amb} y qué haces por miedo a perderlo; elige un control o un hábito compulsivo y suspéndelo durante siete días."},

16:{kern:"la resistencia a la verdad incómoda",obj:"la estructura",bloq:"derrumbar",cuando:"cuando se sostiene una estructura agotada",comp:"romper por impulso y provocar crisis",
hipoC:"sostienes estructuras agotadas y niegas las señales",hiperC:"rompes por impulso y dramatizas la crisis",
nec:"vivir en estructuras verdaderas, aunque haya que desmontar lo que no sirve",
miedo:"el colapso, perder lo construido o la crisis que traería la verdad",
trig:["descubres una verdad incómoda","una estructura (trabajo, relación, creencia) muestra grietas","sientes encierro en algo rígido","alguien te engaña o te traiciona","llega un cambio brusco e inesperado"],
pens:"«Si no lo miro, no se cae»",
cond:"sostienes relaciones, trabajos o creencias agotadas y niegas las señales de crisis",
cons:"la tensión se acumula hasta que la estructura cae de golpe, con más daño del necesario",
necH:"liberarte de la tensión provocando el cambio",
exc:"rompes por impulso, dramatizas las crisis o generas inestabilidad para sentir movimiento",
consH:"destruyes lo que podía repararse y vives en crisis recurrentes",
ciclo:["niegas las grietas","la tensión se acumula","la estructura colapsa","rompes todo para sentir alivio","el caos da miedo al cambio y vuelves a negar"],
cicloTxt:"Negar las grietas acumula presión hasta el colapso; el alivio de romper se vuelve hábito y genera caos, y el miedo al caos lleva de nuevo a sostener lo que no funciona.",
eq:["reconoces las grietas a tiempo","desmontas lo que no sirve con criterio","reconstruyes sobre bases verdaderas","dices verdades incómodas con cuidado"],
integ:"Cuando aparece una verdad incómoda, no la niegas ni lo haces estallar todo: la nombras, evalúas qué se puede reparar y desmontas solo lo que ya no sirve.",
sHipo:["justificas situaciones que sabes insostenibles","evitas mirar problemas evidentes","te sorprenden crisis que otros veían venir","toleras engaños para no romper"],
sHiper:["tus decisiones importantes son abruptas","te atraen las crisis","dices verdades de forma hiriente","te aburres cuando todo está estable"],
prog:["detectas los problemas antes de que estallen","haces cambios profundos sin destruir","tu honestidad cuida a los demás","reconstruyes con más solidez después de una crisis","toleras la estabilidad sin buscar sacudidas"],
preg:["¿Qué estructura de mi vida sé que ya no funciona?","¿Qué verdad estoy evitando mirar?","¿Cuándo rompo para no sentir la tensión?","¿Qué puedo reparar en lugar de destruir?"],
acc:"Haz una lista de lo que sostienes {amb} que ya no funciona; elige una sola cosa, define qué se desmonta y qué se conserva, y da el primer paso este mes."},

17:{kern:"la idealización",obj:"la visión y la inspiración",bloq:"desdibujar",cuando:"cuando la visión no se lleva a la práctica",comp:"idealizar y buscar admiración",
hipoC:"ocultas tu talento y pierdes la esperanza",hiperC:"idealizas y buscas admiración",
nec:"expresar tu autenticidad y creer en una visión que te inspire",
miedo:"que tu talento no valga o que la realidad destruya tus ideales",
trig:["tienes que mostrar tu trabajo o tu talento","alguien critica tu visión","la realidad no está a la altura de tus expectativas","ves brillar a otras personas","un proyecto inspirador exige trabajo rutinario"],
pens:"«Lo que hago no es especial; nadie lo va a valorar»",
cond:"ocultas tus talentos, pierdes la esperanza o renuncias a tus sueños antes de intentarlos",
cons:"tu potencial queda invisible y la vida pierde sentido y color",
necH:"sostener la esperanza a través del ideal y de la admiración ajena",
exc:"idealizas personas o proyectos, buscas reconocimiento y te quedas en la inspiración sin ejecutar",
consH:"llegan decepciones cuando la realidad no coincide, y los proyectos no se concretan",
ciclo:["no crees en tu valor","ocultas tu talento","la falta de sentido duele","idealizas un proyecto o a una persona","la decepción confirma que tu visión no vale"],
cicloTxt:"Ocultar el talento deja un vacío de sentido que se llena idealizando; cuando la realidad no alcanza el ideal, la decepción confirma la creencia de que la propia visión no tiene valor.",
eq:["muestras tu trabajo aunque no sea perfecto","conviertes la visión en pasos concretos","inspiras sin necesitar admiración","mantienes la esperanza con realismo"],
integ:"Cuando la realidad decepciona tu ideal o alguien critica tu visión, no te escondes ni te refugias en el sueño: ajustas la visión y das el siguiente paso concreto.",
sHipo:["tienes talentos que casi nadie conoce","sientes desesperanza frente al futuro","comparas tu trabajo con el de otros y lo desvalorizas","abandonas sueños antes de intentarlos"],
sHiper:["te entusiasmas con ideas o personas y luego te decepcionas","necesitas que admiren lo que haces","tienes muchos proyectos inspiradores sin ejecutar","te cuesta la rutina de concretar"],
prog:["compartes tu talento con regularidad","tus proyectos pasan de la idea a la realidad","valoras a personas reales, no a ideales","tu esperanza sobrevive a las decepciones","inspiras con hechos"],
preg:["¿Qué talento escondo?","¿A quién o qué idealizo?","¿Qué visión necesita un primer paso concreto?","¿Cuánto depende mi motivación del reconocimiento ajeno?"],
acc:"Muestra esta semana algo que creaste {amb} a al menos una persona, sin pulirlo más, y anota qué sentiste antes y después."},

18:{kern:"la incertidumbre",obj:"la percepción emocional",bloq:"nublar",cuando:"cuando las emociones se interpretan sin contraste",comp:"perderse en miedos, fantasías o proyecciones",
hipoC:"desconfías de tus emociones y lo racionalizas todo",hiperC:"te pierdes en miedos y fantasías",
nec:"espacio para sentir e imaginar, y seguridad emocional",
miedo:"lo desconocido, el engaño o el abandono",
trig:["una situación es ambigua o falta información","alguien se distancia sin explicación","recibes un mensaje que puede interpretarse de varias formas","enfrentas algo nuevo sin garantías","sientes que te ocultan algo"],
pens:"«Las emociones no sirven; mejor lo analizo con lógica»",
cond:"lo racionalizas todo, desconfías de lo que sientes y evitas las situaciones inciertas",
cons:"pierdes información valiosa de tu intuición y vives con una ansiedad difusa y sin nombre",
necH:"llenar la incertidumbre con alguna explicación",
exc:"imaginas escenarios, proyectas miedos y crees interpretaciones sin verificarlas",
consH:"reaccionas a lo que imaginas, no a lo que pasa; aparecen conflictos y desconfianza",
ciclo:["hay incertidumbre","desconfías de lo que sientes","la ansiedad crece","imaginas y proyectas miedos","reaccionar a lo imaginado genera más incertidumbre"],
cicloTxt:"Racionalizar para no sentir deja la ansiedad sin nombre; cuando desborda, se llena con interpretaciones y miedos proyectados que, al actuar sobre ellos, generan más confusión.",
eq:["das espacio a tus emociones y luego verificas","preguntas antes de interpretar","usas tu imaginación de forma creativa","toleras no saber"],
integ:"Cuando algo es ambiguo, no te lo tragas ni te pierdes en suposiciones: nombras lo que sientes, haces una pregunta directa y decides con la información real.",
sHipo:["te cuesta nombrar lo que sientes","lo explicas todo con lógica","evitas lo incierto","sientes ansiedad sin saber por qué"],
sHiper:["imaginas lo peor a partir de detalles","interpretas silencios o mensajes","desconfías sin pruebas","te asaltan miedos difíciles de explicar"],
prog:["preguntas en lugar de suponer","tus intuiciones se confirman al verificarlas","toleras la incertidumbre sin angustia","tu imaginación produce creaciones","reconoces cuándo un miedo es una proyección"],
preg:["¿Qué estoy suponiendo sin haber preguntado?","¿Qué siento y estoy racionalizando?","¿Qué miedo se repite en situaciones distintas?","¿Qué dato me falta para decidir?"],
acc:"La próxima vez que algo sea ambiguo {amb}, escribe tu interpretación, haz una pregunta directa para verificarla y compara el resultado con lo que imaginaste."},

19:{kern:"la necesidad de reconocimiento",obj:"la visibilidad y la alegría",bloq:"eclipsar",cuando:"cuando la propia presencia se esconde",comp:"buscar atención constante y depender del aplauso",
hipoC:"ocultas tu presencia y temes destacar",hiperC:"buscas atención y dependes de la aprobación",
nec:"brillar, expresarte y sentir que tu presencia aporta calidez y claridad",
miedo:"pasar desapercibido o no merecer reconocimiento",
trig:["tienes que exponerte ante un grupo","alguien recibe el reconocimiento que esperabas","tu trabajo no es visto","te elogian en público","hay que liderar algo visible"],
pens:"«Mejor que no me vean; no merezco tanto»",
cond:"te escondes, minimizas tus logros y cedes el protagonismo aunque te corresponda",
cons:"tu aporte pasa desapercibido y crece la sensación de no merecer",
necH:"confirmar tu valor a través de la mirada ajena",
exc:"buscas atención constante, sobreestimas tu posición o necesitas aplausos para sostenerte",
consH:"tu ánimo depende de la respuesta externa y los demás sienten que no hay espacio para ellos",
ciclo:["sientes que no mereces","te escondes","tu aporte no se ve","buscas atención para compensar","depender del aplauso vuelve frágil tu autoestima"],
cicloTxt:"Esconderse vuelve invisible el aporte; la falta de reconocimiento se compensa buscando atención, y cuando el aplauso falta, la autoestima cae y vuelve el impulso de esconderse.",
eq:["muestras tus logros sin exagerar ni minimizar","compartes el mérito","tu alegría no depende del aplauso","lideras con calidez"],
integ:"Cuando no recibes el reconocimiento esperado, no te apagas ni reclamas atención: reconoces tu aporte, lo comunicas con claridad y sigues brillando en lo que haces.",
sHipo:["minimizas tus logros cuando te felicitan","evitas exponerte","dejas que otras personas se lleven el mérito","te cuesta decir «lo hice bien»"],
sHiper:["necesitas ser el centro de atención","te afecta mucho que no te elijan","tu ánimo sube o baja según los elogios","te cuesta escuchar sin hablar de ti"],
prog:["aceptas los elogios con sencillez","celebras los logros de otros","te expones sin miedo excesivo","tu autoestima es estable","tu presencia da energía a los demás"],
preg:["¿Dónde me escondo aunque podría brillar?","¿Cuánto depende mi ánimo del reconocimiento?","¿Con quién comparto el mérito?","¿Qué logro no me he permitido celebrar?"],
acc:"Comparte esta semana un logro {amb} con alguien, sin minimizarlo ni exagerarlo, y reconoce en voz alta el aporte de otra persona."},

20:{kern:"la autocrítica severa",obj:"el llamado interno",bloq:"someter a juicio",cuando:"cuando una decisión vital se posterga por culpa",comp:"juzgar con severidad e intentar salvar a otros",
hipoC:"ignoras llamados importantes y te quedas en la culpa",hiperC:"juzgas con severidad o intentas salvar a otros",
nec:"resolver lo pendiente y comprobar que tu vida responde a un llamado propio",
miedo:"haber desperdiciado tu vida, la culpa o equivocarte con tu vocación",
trig:["recuerdas un error del pasado","sientes un llamado a cambiar de vida","alguien cercano está en problemas","te enfrentas a asuntos familiares pendientes","te piden una decisión definitiva"],
pens:"«Ya es tarde; no merezco otra oportunidad»",
cond:"ignoras los llamados internos, postergas decisiones vitales y te quedas en la culpa por el pasado",
cons:"la vida se siente sin propósito y los asuntos pendientes se acumulan",
necH:"reparar el pasado y darle sentido a todo",
exc:"te juzgas con dureza, intentas salvar a otros o conviertes cada experiencia en una misión obligatoria",
consH:"te agotas cargando responsabilidades ajenas y los vínculos se vuelven una tarea",
ciclo:["sientes culpa por el pasado","postergas el llamado","crece la sensación de desperdicio","te exiges o intentas salvar a otros","el agotamiento renueva la culpa"],
cicloTxt:"La culpa paraliza la respuesta al llamado; la sensación de desperdicio se compensa con exigencia o rescatando a otros, y el agotamiento resultante alimenta una nueva culpa.",
eq:["revisas el pasado para aprender, no para castigarte","respondes a tu vocación paso a paso","ayudas sin salvar","cierras los asuntos pendientes"],
integ:"Cuando vuelve un error del pasado o un llamado a cambiar, no te castigas ni lo ignoras: reconoces lo aprendido, perdonas lo que corresponde y das un paso elegido hacia lo que te llama.",
sHipo:["sientes que ya es tarde para lo que deseas","te acompaña la culpa por decisiones pasadas","ignoras señales de que necesitas un cambio","postergas conversaciones familiares"],
sHiper:["te juzgas con mucha dureza","asumes la tarea de rescatar a otros","todo se vuelve una misión","corriges a los demás"],
prog:["hablas del pasado sin culpa","das pasos concretos hacia tu vocación","ayudas sin cargar con la vida ajena","cierras asuntos familiares pendientes","te das segundas oportunidades"],
preg:["¿Qué llamado estoy ignorando?","¿Qué culpa sigo cargando?","¿A quién intento salvar, y para qué?","¿Qué asunto pendiente puedo cerrar?"],
acc:"Escribe un asunto pendiente {amb}; decide qué parte te corresponde, da un paso de cierre esta semana y escribe una frase de perdón hacia ti."},

21:{kern:"la tendencia a abarcar demasiado",obj:"la integración y el cierre",bloq:"dispersar",cuando:"cuando los procesos quedan inconclusos",comp:"querer abarcarlo todo y no detenerse",
hipoC:"temes exponerte y dejas procesos inconclusos",hiperC:"abarcas demasiado y no sabes detenerte",
nec:"expansión, sentido de totalidad y cerrar ciclos con aprendizaje",
miedo:"no estar a la altura de un escenario amplio, o quedarte en un mundo pequeño",
trig:["se abre una oportunidad en un escenario más amplio","un proyecto está casi terminado","tienes que elegir un foco entre muchas opciones","sientes que tu entorno te queda pequeño","terminas algo importante"],
pens:"«Todavía no es suficiente para mostrarlo»",
cond:"dejas procesos sin terminar, evitas exponerte a escenarios amplios y postergas el cierre",
cons:"acumulas ciclos abiertos y sientes que tu potencial no se realiza",
necH:"sentir que abarcas y dominas el conjunto",
exc:"te dispersas en muchos escenarios, sumas proyectos y no sabes detenerte después de lograr",
consH:"pierdes foco, pertenencia y la satisfacción de lo logrado",
ciclo:["temes no estar a la altura","dejas procesos abiertos","sientes que no te realizas","abarcas demasiado para compensar","la dispersión impide cerrar y vuelve el temor"],
cicloTxt:"Postergar el cierre deja ciclos abiertos; la sensación de no realizarse se compensa sumando escenarios, y la dispersión impide terminar lo que daría la sensación de logro.",
eq:["terminas lo que empiezas antes de expandirte","eliges un foco","celebras los cierres","te expandes sin perder pertenencia"],
integ:"Cuando se abre algo más grande o sientes que no llegas, no postergas ni te dispersas: cierras lo que tienes pendiente, eliges un foco y das el siguiente paso.",
sHipo:["tienes proyectos casi terminados que no cierras","evitas mostrar tu trabajo fuera de tu entorno","sientes que nunca es suficiente","postergas la entrega, el lanzamiento o la graduación"],
sHiper:["tienes demasiados frentes abiertos","después de un logro empiezas otra cosa sin pausa","te cuesta pertenecer a un solo lugar","sientes una dispersión constante"],
prog:["cierras ciclos y los celebras","te expones en escenarios más amplios","tienes un foco claro","disfrutas lo logrado antes de seguir","integras experiencias diversas en un todo coherente"],
preg:["¿Qué ciclo tengo casi terminado?","¿Dónde me estoy dispersando?","¿Qué escenario más amplio evito?","¿Qué necesito cerrar antes de expandirme?"],
acc:"Elige un proceso casi terminado {amb} y ciérralo este mes; no empieces nada nuevo en ese ámbito hasta terminarlo y celebrar el cierre."},

22:{kern:"la necesidad de libertad sin compromiso",obj:"la espontaneidad",bloq:"desestabilizar",cuando:"cuando la libertad se usa para evitar el compromiso",comp:"dispersarse y evadir las consecuencias",
hipoC:"temes comenzar y te aferras a la seguridad",hiperC:"te dispersas y evitas el compromiso",
nec:"libertad, espontaneidad y la posibilidad de explorar caminos nuevos",
miedo:"sentir encierro en una estructura o, al contrario, el vacío de no tener dónde apoyarte",
trig:["te imponen reglas o rutinas","aparece una posibilidad nueva y excitante","tienes que comprometerte a largo plazo","algo se vuelve predecible","te piden rendir cuentas"],
pens:"«Mejor lo seguro, aunque me aburra»",
cond:"te aferras a la seguridad, evitas empezar y pierdes contacto con tu curiosidad",
cons:"la vida se vuelve gris y aparece la sensación de vivir la vida de otra persona",
necH:"no perder la libertad",
exc:"te dispersas, evitas las consecuencias y confundes libertad con ausencia de compromiso",
consH:"los proyectos y los vínculos no se sostienen y aparece inestabilidad",
ciclo:["temes arriesgar","te aferras a lo seguro","el aburrimiento se vuelve encierro","escapas hacia una libertad sin compromiso","la inestabilidad asusta y vuelves a lo seguro"],
cicloTxt:"La seguridad excesiva se vive como encierro; el escape hacia la libertad total genera inestabilidad, y esa inestabilidad empuja de vuelta a una seguridad que vuelve a asfixiar.",
eq:["exploras con una estructura mínima","te comprometes eligiendo tu forma","asumes las consecuencias de tus decisiones","mantienes la curiosidad dentro de la rutina"],
integ:"Cuando sientes encierro o aparece algo nuevo y excitante, no huyes ni te resignas: exploras dentro de un marco que te permita sostener lo que eliges.",
sHipo:["hace mucho que no haces algo por primera vez","eliges lo seguro aunque te aburra","sientes que vives la vida que otros esperan","reprimes impulsos de explorar"],
sHiper:["cambias de planes a último momento","evitas los compromisos largos","te cuesta asumir consecuencias","empiezas muchas cosas y terminas pocas"],
prog:["exploras sin descuidar responsabilidades","sostienes compromisos que elegiste","tu espontaneidad da frescura a tus vínculos","asumes riesgos calculados","terminas lo que empiezas sin perder libertad"],
preg:["¿De qué estoy huyendo cuando busco libertad?","¿Qué seguridad me está asfixiando?","¿Qué compromiso podría elegir a mi manera?","¿Qué consecuencia estoy evitando?"],
acc:"Haz esta semana algo nuevo {amb} dentro de un límite concreto (tiempo, dinero o alcance) y sostenlo hasta el final del plazo que te pusiste."}
};
